<?php

require_once DRUPAL_ROOT . '/modules/filter/filter.module';

function capacity_menu()
{
  $menu['capacity/add'] = array
  (
    'title' => 'capacity',
    'page callback' => 'capacity_item_form_add',
    'access arguments' => array('add capacity items'),
    'access callback' => TRUE,
  );


  $menu['capacity/edit'] = array
  (
    'title' => 'capacity',
   'page callback' => 'capacity_edit_item_page',
    'access callback' => TRUE,
  );



  $menu['capacity/%capacity/edit'] = array
  (
    'title' => 'Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('capacity_edit_item_form', 1),
    'access arguments' => array('edit capacity items'),
     'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
  'weight' => -1,
  );

  $menu['capacity/list'] = array
  (
    'title' => 'Capacity',
    'page callback' => 'capacity_view_list_item_page',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );

    $menu['capacity/add_resource'] = array
  (
    'title' => 'Add Resource',
    'page callback' => 'capacity_view_add_resource_page',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );

   $menu['capacity/schedule_meeting'] = array
  (
    'title' => 'Schedule Meeting',
    'page callback' => 'capacity_view_schedule_meeting_page',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );

  $menu['capacity/%capacity'] = array
  (
    'title' => 'View capacity',
      'page callback' => 'capacity_view_item_page',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );

  $menu['capacity/%capacity/view'] = array
  (
    'title' => 'View',
    'page callback' => 'drupal_get_form',
    'access callback' => TRUE,
    'page arguments' => array('capacity_item_view_form', 1),
    'access arguments' => array('edit capacity items'),
    'type' => MENU_LOCAL_TASK,
  'weight' => -2,
  );
  $menu['capacity/capacity/delete'] = array
  (
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('capacity_item_delete_form', 1),
    'access arguments' => array('delete mymodule items'),
    'type' => MENU_LOCAL_TASK,
  );

  $menu['capacity/get-event-details/%'] = array
  (
    'title' => 'Event Details',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('get_event_details', 1),
    'access callback' => TRUE,
  );

  return $menu;
}

function capacity_init(){
  drupal_add_js(libraries_get_path('timepicker') . '/js/jquery.ui.timepicker.js');
  drupal_add_css(libraries_get_path('timepicker') . '/css/jquery.ui.timepicker.css');
}

function get_event_details(){

    global $base_url;
    $form=array();
  $url = (isset($_SERVER['HTTPS']) ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
     $nodeId= basename($url);
    if(isset($nodeId) && $nodeId!=""){
        $event_details = db_query("SELECT * FROM {capacity_details} WHERE event_node_id = " . $nodeId."")->fetchAll();
    }

    if(isset($event_details) && count($event_details)==0){
        $event_details = db_query("SELECT * FROM {implementation_details} WHERE event_node_id = " . $nodeId."")->fetchAll();
    }

	$created_by_img = file_create_url(path_to_theme().'/images/report.png');

    if(isset($event_details) && count($event_details)>0){
         if(isset($event_details[0]->Record) && $event_details[0]->Record=='Record Meeting'){
              $eventTitle=$event_details[0]->Record_meeting;
              $eventType="Meeting";
         }else if(isset($event_details[0]->Record_tranning) && $event_details[0]->Record_tranning!=''){
              $eventTitle=$event_details[0]->Record_tranning;
              $eventType="Record Training / Techinical Assistance";
         }

     if(isset($event_details[0]->csap_6) || isset($event_details[0]->csap_7)){
         if(isset($event_details[0]->csap_6) && $event_details[0]->csap_6!=''){
                 $eventTitle="CSAP 6 - ".$event_details[0]->csap_6;
                 $eventType="CSAP 6";
         }else{
                 $eventTitle="CADCA 7 - ".$event_details[0]->csap_7;
                 $eventType="CADCA 7";
         }
       }
         $startDate=$event_details[0]->startdatetime;
         $endDate=$event_details[0]->enddatetime;
         $location=$event_details[0]->location;
         $dPurpose=$event_details[0]->description_of_purpose;
         //$type=$event_details[0]->type;
         //$category=$event_details[0]->category;

         if((isset($event_details[0]->Record) && $event_details[0]->Record=='Record Meeting') || ($event_details[0]->Record=='Record Training/Technical Assistance')){
              $eventStatus=(isset($event_details[0]->is_pending) && $event_details[0]->is_pending=="yes")?"Pending":"Completed";
              //$cap_id=$event_details[0]->capacity_id;
              $customLink=$base_url.'/capacity/'.$event_details[0]->capacity_id.'/edit';
              $editLinkHtml="<div class='submit_button'><a target='_blank' class='form-submit' href=$customLink><img src='$created_by_img' class='white_img'><span>Click here to view Report</span></a></div>";
         }else{
              $eventStatus=(isset($event_details[0]->is_pending) && $event_details[0]->is_pending=="1")?"Completed":"Pending";
              //$imp_id=$event_details[0]->implementation_id;
              $customLink=$base_url.'/implementation/'.$event_details[0]->implementation_id.'/edit';
              $editLinkHtml="<div class='submit_button'><a target='_blank' class='form-submit' href=$customLink><img src='$created_by_img' class='white_img'><span>Click here to view Report</span></a></div>";
         }

         $attachments=$event_details[0]->Attachments_fid;
         $notes=$event_details[0]->Attachments_notes;

         if(isset($event_details[0]->personConductingContent)){
                $personConducting=unserialize($event_details[0]->personConductingContent);
         }
         if(isset($event_details[0]->Members_Invloved)){
                 $membersInvolved=unserialize($event_details[0]->Members_Invloved);
         }
         //echo "<pre>";print_r($event_details);die;
         $all_user_lists = entity_load('user');
         $all_user_details = json_decode(json_encode($all_user_lists), true);

        $personsRow='';
        foreach($all_user_details as $usersList){ //echo "<pre>";print_r($usersList);die;
            if($usersList['uid']!="0" && isset($usersList['roles'][7]) && $usersList['roles'][7]=="Staff User"){

              $last_name_staff = db_query("SELECT field_last_name_value FROM field_data_field_last_name WHERE entity_id =".$usersList['uid'])->fetchField();

              if(in_array($usersList['uid'],$personConducting['person_conducting'])){
                      $personsRow.='<span>'.(($usersList['name']!="")?$usersList['name']:"").'</span>';
              }
            }

        }

        $membersRow='';
        foreach($all_user_details as $membersList){ //echo "<pre>";print_r($usersList);die;
            if($membersList['uid']!="0" && $membersList['roles'][7]!="Staff User"){

              $last_name_staff = db_query("SELECT field_last_name_value FROM field_data_field_last_name WHERE entity_id =".$usersList['uid'])->fetchField();

              if(in_array($membersList['uid'],$membersInvolved['Members_Invloved'])){
                      $membersRow.='<span>'.(($membersList['name']!="")?$membersList['name']:"").'</span>';
              }
            }

        }

    if(isset($event_details[0]->Attachments_fid) && $event_details[0]->Attachments_fid!=''){
    	$upload_ids=unserialize($event_details[0]->Attachments_fid);
    }
        $fileAttachments='';
    if(isset($upload_ids['upload_id']) && count($upload_ids['upload_id'])>0){

    	foreach($upload_ids['upload_id'] as $uploadId){
    		$fid=$uploadId;
    		$file_upload_details = db_query("SELECT * FROM {file_managed} WHERE fid = ".$fid)->fetchAll();

    		$fURI=$file_upload_details[0]->uri;
    		$fname=$file_upload_details[0]->filename;
    		$fileURI=file_create_url($fURI);
      		if($fname!=""){
      				$fileAttachments.='<div class="upload_data"><a target="_blank" href='.$fileURI.'> <i class="fa fa-cloud-download" aria-hidden="true"></i> '.$fname.'</a> </div>';
          }
       }

    }

        $locationHtml=($location!='')?"<div class='event_details'><h5>Location: </h5><p>".$location."</p></div>":'';
        $typeHtml=($eventType!='')?"<div class='event_details'><h5>Type: </h5><p>".$eventType."</p></div>":'';
        $categoryHtml=($category!='')?"<div class='event_details'><h5>Category: </h5><p>".$category."</p></div>":'';
        $personHtml=($personsRow!='')?"<div class='event_details'><h5>Person Conducting: </h5><p>".$personsRow."</p></div>":'';
        $memberHtml=($membersRow!='')?"<div class='event_details'><h5>Members Involved: </h5><p>".$membersRow."</p></div>":'';
        $contactHtml=($contactsInolved!='')?"<div class='event_details'><h5>Contacts Involved: </h5><p>".$contactsInolved."</p></div>":'';
        $dPurposeHtml=($dPurpose!='')?"<div class='event_details'><h5>Description of purpose: </h5><p>".$dPurpose."</p></div>":'';
        $attachmentsHtml=($fileAttachments!='')?"<div class='event_details'><h5>Files: </h5><p>".$fileAttachments."</p></div>":'';
        $notesHtml=($notes!='')?"<div class='event_details'><h5>Notes: </h5><p>".$notes."</p></div>":'';
        $eventStatusHtml=($eventStatus!='')?"<div class='event_details'><h5>Report Status: </h5><p>".$eventStatus."</p></div>":'';

      $form['event-start-html']=array('#markup'=>"
                                <div class='event_details'><h5>Title </h5><p>".$eventTitle."</p></div>
                                  <div class='event_details'><h5>Date of Service: </h5><p>".$startDate."</p></div>
                                  $locationHtml $typeHtml $categoryHtml $personHtml $memberHtml $contactHtml $dPurposeHtml $attachmentsHtml $notesHtml $eventStatusHtml
                                  $editLinkHtml
                               ");

   }else{
       $form['not-found-event']=array("#markup"=>"<div><h4>Event not found.</h4></div>");
   }

      echo drupal_render($form);exit();

  //echo "<pre>";print_r(drupal_render($form));die;
}


function capacity_load($capacity_id)
{
  return db_query('SELECT capacity_id,contributing_factor_models,intervention_models,Record,Record_meeting,Record_tranning,startdatetime,enddatetime,Length_of_services,location,country,address_1,address_2,city,states,zip_code,number_adult_served,number_youth_served,Number_Business_Attending,Members_Invloved,personConductingContent,contactContent,description_of_purpose,description_of_outcome,Donation_select,Monetary_Value,Comment,Attachments_notes,Attachments_fid,signature,is_pending FROM {capacity_details} WHERE capacity_id = :capacity_id', array(':capacity_id' => $capacity_id))
  ->fetchObject();
}



function capacity_item_form_add()
{
  $item = new StdClass;
  $item->capacity_id = FALSE;
  $item->Record = '';
  $item->Record_meeting = '';
  $item->Record_tranning = '';
  $item->personConductingContent = '';
  $item->startdatetime = '';
  $item->enddatetime = '';
  $item->Length_of_services = '';
  $item->location = '';
  $item->capacity_address = '';
  $item->Country = '';
  $item->address_1 = '';
  $item->address_2 = '';
  $item->city = '';
  $item->states = '';
  $item->zip_code = '';
  $item->number_adult_served = '';
  $item->number_youth_served = '';
  $item->Number_Business_Attending = '';
  $item->Members_Invloved = '';
  $item->description_of_purpose = '';
  $item->description_of_outcome = '';
  $item->Donation_select = '';
  $item->Monetary_Value = '';
  $item->Comment = '';
  $item->Attachments_fid = '';
  $item->Attachments_notes = '';
  $item->signature = '';
  return drupal_get_form('capacity_item_form', $item);
}

function capacity_edit_item_page()
{
  $item = new StdClass;
  $item->capacity_id = '';
  $item->Record = '';
  $item->Record_meeting = '';
  $item->Record_tranning = '';
  $item->personConductingContent = '';
  $item->startdatetime = '';
  $item->enddatetime = '';
  $item->Length_of_services = '';
  $item->location = '';
  $item->capacity_address = '';
  $item->Country = '';
  $item->address_1 = '';
  $item->address_2 = '';
  $item->city = '';
  $item->states = '';
  $item->zip_code = '';
  $item->number_adult_served = '';
  $item->number_youth_served = '';
  $item->Number_Business_Attending = '';
  $item->Members_Invloved = '';
  $item->description_of_purpose = '';
  $item->description_of_outcome = '';
  $item->Donation_select = '';
  $item->Monetary_Value = '';
  $item->Comment = '';
  $item->Attachments_fid = '';
  $item->Attachments_notes = '';
  $item->signature = '';
  return drupal_get_form('capacity_edit_item_form', $item);
}



function capacity_item_view_form($form, &$form_state, $item)
{
// Add CSS and JS files, add some markup

  //$html = 'scripts[] = misc/jquery.js';
    $form = array();
    $form['#tree'] = TRUE;
    $form['#attributes']['enctype'] = 'multipart/form-data';

    drupal_set_title("Capacity View Page");

  $form['#item'] = $item;
   $contributing_factor = db_query("SELECT tid, name FROM {taxonomy_term_data} WHERE vid = 12")->fetchAll();

    $interventions = db_query("SELECT tid, name FROM {taxonomy_term_data} WHERE vid = 28")->fetchAll();


  //$planning_lists = db_query("SELECT planning_id, title FROM {planning_details}")->fetchAll();
      $query = db_select('planning_details','a');
      $query->fields('a', array('planning_id','title'));
      $query->orderBy('a.title','ASC');
      $planning_lists = $query->execute()->fetchAll();
      $planCount=0;$lmCount=0;
      foreach($planning_lists as $plankey=>$planVal){
    $plan_id=$planVal->planning_id;
    $plan_title=$planVal->title;
    $planning_data_lists = db_query("SELECT * FROM {planning_details} WHERE planning_id = ".$plan_id)->fetchAll();


    $chkSerialize = @unserialize($planning_data_lists[0]->contributing_factor);
    if ($chkSerialize !== false) {
      $contributingFactor=unserialize($planning_data_lists[0]->contributing_factor);
        $interventionsCheckedItems=unserialize($planning_data_lists[0]->interventions);
        $logicModelCount=count($contributingFactor['contributingCollection']);
        //echo $logicModelCount."<pre>";print_r($contributingFactor);echo "<pre>";print_r($interventionsCheckedItems);die;
      $conSelectedItems="";$intSelectedItems="";
    //$contributingItems="";
     $contributingItems='<div id="firstTable_'.$plankey.'" class="heading_tag">
								<h3>'.$plan_title.' </h3>
								<div class="select_btn">
									<div class="form-checkboxes">
										<div class="form-item form-type-checkbox" style="display:none;">
											<label><input id="checkAllLogicModel" type="checkbox" value="" name="contributing_factor" class="form-checkbox" onchange="checkAllFunc(this,'.$planCount.')"> Select all/Select none</label>
										</div>
									</div>
								</div>
						 </div>
	<div class="logicmodel_inter_con" id="logicmodel_inter_con_'.$planCount.'">';
     $planCount++;
      $ico=1;//echo $logicModelCount;die;


       $unCFValues=unserialize($item->contributing_factor_models);
       $unINValues=unserialize($item->intervention_models);//echo "<pre>";print_r($unINValues);die;

       for($i=0;$i<$logicModelCount;$i++){
		//if($i==0){ $i=1; }
         $ichange=$plankey.'_'.$i;
         //$contributingItems.='<table id="firstTable_'.$i.'">';

        $contributingItems.='<div class="capacity_logic_section"><div id="conFactorTable_'.$i.'" class="conFactorTab">
                            <div class="form-type-checkboxes"><label class="heading_label">Contributing Factor</label>';
      foreach($contributing_factor as $fKey=>$fVal){
          if($fVal->name==trim($contributingFactor['contributingCollection']['contribCollection'.$i])){
			  $cfCheck=($unCFValues['contributing_factor']['contributing_factor'.$ichange]==$fVal->tid)?'checked':'';
            $contributingItems.='<div class="form-checkboxes">
									<div class="form-item form-type-checkbox"><label><input disabled="disabled" type="checkbox" value="'.$fVal->tid.'" class="form-checkbox" name="contributing_factor'.$ichange.'" '.$cfCheck.'><span> '.$fVal->name.'</span></label>
									</div>
								</div>';
          }

      }
      $contributingItems.='</div></div>
      <div id="intervTable_'.$i.'" class="interventions intervTab">
                           <div class="form-type-checkboxes"><label class="heading_label">Interventions</label>
      ';

      foreach($interventions as $cKey=>$cVal){ //echo "<pre>";print_r($unINValues['interventions']['interventions'.$ichange]);die;
           if(in_array($cVal->name,$interventionsCheckedItems['interventionCollection']['internCollection'.$i])){
			   $inCheck=(in_array($cVal->tid,$unINValues['interventions']['interventions'.$ichange])  && $cfCheck)?'checked':'';
            $contributingItems.='<div class="form-checkboxes">
                                <div class="form-item form-type-checkbox"><label><input disabled="disabled" type="checkbox" value="'.$cVal->tid.'" class="form-checkbox" name="interventions'.$ichange.'[]" '.$inCheck.'><span> '.$cVal->name.' </span></label></div>
                     </div>';
           }

      }

      $contributingItems.='</div></div></div>';

      //$contributingItems.='</table>';

        #--------------------------------------
        # create a "planning logic model" fieldset
        #--------------------------------------
        $form['planningLogicModel'.$plankey] = array(
        '#type' => 'fieldset',
        '#title' => t($plan_title),
        '#collapsible' => TRUE,
        '#collapsed' => ($plankey=="0")?FALSE:TRUE,
        );

      $ico++;


}

  $contributingItems.='</div></table>';
    $form['planningLogicModel'.$plankey]['contributing_intervention'.$plankey] =array(
    "#title"  => 'Logic model',
    "#markup"=> $contributingItems
    );

    $form['table_count_id']=array(
      '#type'=>"hidden",
      '#value'=>($logicModelCount-1),
      '#attributes'=>array("id"=>"LogicModelCountId")
    );


        //echo "<pre>";print_r($contributingFactor);echo "<pre>";print_r($interventionsCheckedItems);die;
    } else {
      $ichange=$plankey.'_'.$lmCount;
       $unCFValues=unserialize($item->contributing_factor_models);
       $unINValues=unserialize($item->intervention_models);//echo "<pre>";print_r($unINValues);die;

      $contributingFactor=$planning_data_lists[0]->contributing_factor;
      $interventionsCheckedItems=explode(",",$planning_data_lists[0]->interventions);

      $contributingItems="";
    foreach($contributing_factor as $fKey=>$fVal){
        if($contributingFactor==$fVal->name){ //echo $unCFValues['contributing_factor']['contributing_factor'.$ichange]."-->".$contributingFactor;die;
			$cfCheck=($unCFValues['contributing_factor']['contributing_factor'.$ichange]==$fVal->tid)?'checked':'';
          $contributingItems.='<div class="form-checkboxes">
									<div class="form-item form-type-checkbox"><label><input disabled="disabled" type="checkbox" class="form-checkbox" value="'.$fVal->tid.'" name="contributing_factor" '.$cfCheck.'><span> '.$fVal->name.' </span></label>
									</div>
								</div>';
        }
    }

    $interventionsItems="";
    foreach($interventions as $cKey=>$cVal){ //echo $cVal."<pre>";print_r($interventionsCheckedItems);die;
         if(in_array($cVal->name,$interventionsCheckedItems)){
			 $inCheck=(in_array($cVal->tid,$unINValues['interventions']['interventions'.$ichange]))?'checked':'';
          $interventionsItems.='<div class="form-checkboxes">
									<div class="form-item form-type-checkbox"><label><input disabled="disabled" type="checkbox" value="'.$cVal->tid.'" class="form-checkbox" name="interventions[]" '.$inCheck.'><span> '.$cVal->name.' </span></label>
									</div>
								</div>';
         }
    }
        #--------------------------------------
        # create a "planning logic model" fieldset
        #--------------------------------------
        $form['planningLogicModel'.$plankey] = array(
        '#type' => 'fieldset',
        '#title' => t($plan_title),
        '#collapsible' => TRUE,
        '#collapsed' => ($plankey=="0")?FALSE:TRUE,
        );

    $form['planningLogicModel'.$plankey]['contributing_intervention'.$plankey] =array(
    "#title"  => 'Logic model',
      "#markup"=> '
      <div id="firstTable'.$plankey.'" class="heading_tag">
		  <h3>'.$plan_title.' </h3>
		  <div class="select_btn">
			 <div class="form-checkboxes">
				<div class="form-item form-type-checkbox" style="display:none;">
					<label><input id="checkAllLogicModel" type="checkbox" value="" class="form-checkbox" name="contributing_factor" onchange="checkAllFunc(this,'.$planCount.')"> Select all/Select none</label>
				</div>
			</div>
		</div>
	</div>
	<div class="logicmodel_inter_con" id="logicmodel_inter_con_'.$planCount.'">
          <div class="capacity_logic_section">
               <div id="conFactorTab" class="conFactorTab">
					<div class="form-type-checkboxes">
						<label class="heading_label">Contributing Factor</label>
                            '.$contributingItems.'
                    </div>
				</div>
				<div id="intervTab" class="interventions intervTab">
					<div class="form-type-checkboxes">
						<label class="heading_label">Interventions</label>
                           '.$interventionsItems.'
                    </div>
				</div>
            </div>
        </div>
</table>');

    $form['table_count_id']=array(
      '#type'=>"hidden",
      '#value'=>0,
      '#attributes'=>array("id"=>"LogicModelCountId")
    );

    $planCount++;
    $lmCount++;

    }

}


//echo "<pre>";print_r($item);die;

//csap 6 fields Information Dissemination
    if(isset($item->Record_meeting) && $item->Record_meeting!=''){
            $Record_meeting=$item->Record_meeting;
            $form['Record_meeting_type'] = array(
                '#markup' => '<div class="capacity_view_details1"><h5>Event Type </h5><p>Meeting</p></div>',
            );
    }
    if(isset($item->Record_tranning) && $item->Record_tranning!=''){
            $Record_tranning=$item->Record_tranning;
            $form['Record_meeting_type'] = array(
                '#markup' => '<div class="capacity_view_details1"><h5>Event Type </h5><p>Training/Technical Assistance</p></div>',
            );
    }


//csap 6 fields Information Dissemination
if(isset($item->Record_meeting) && $item->Record_meeting!=''){
  $form['Record_meeting'] = array(
'#markup' => '<div class="capacity_view_details1"><h5>Title of Meeting Event </h5><p>'.$Record_meeting.'</p></div>',
  );
}else{
  $form['Record_tranning'] = array(
  '#markup' => '<div class="capacity_view_details1"><h5>Title of Training/Technical Assistance Event </h5><p>'.$Record_tranning.'</p></div>',
   '#default_value' => $item->Record_tranning,
  );
}


$all_user_lists = entity_load('user');

$all_user_details = json_decode(json_encode($all_user_lists), true);




   if(isset($item->personConductingContent)){
    $personConduct_id_arr=unserialize($item->personConductingContent);
   }
   //echo "<pre>";print_r($personConduct_id_arr);die;


   $form['personConducting']=array('#markup'=>'<div class="responsive_table"><h5>Person Conducting</h5><table id="personConductingTab" class="sticky-enabled table-select-processed">
 <thead><tr><th>First Name</th><th>Last Name</th><th>Email</th><th>Cell phone</th> </tr></thead>
<tbody>');
  $usersRow='';
  foreach($all_user_details as $usersList){ //echo "<pre>";print_r($usersList);die;
      if($usersList['uid']!="0" && isset($usersList['roles'][7]) && $usersList['roles'][7]=="Staff User"){

        $last_name_staff = db_query("SELECT field_last_name_value FROM field_data_field_last_name WHERE entity_id =".$usersList['uid'])->fetchField();
        $cell_phone = db_query("SELECT field_cell_phone_value FROM field_data_field_cell_phone WHERE entity_id =".$usersList['uid'])->fetchField();
        if(in_array($usersList['uid'],$personConduct_id_arr['person_conducting'])){
        $personChkVal=(in_array($usersList['uid'],$personConduct_id_arr['person_conducting']))?'checked="checked"':'';
        $usersRow.='<tr class="odd"><td class="Member-hide" style="display:none"><div class="form-item form-type-checkbox form-item-person-conducting-0">
                <input id="edit-person-conducting-0" name="person_conducting[]" value="'.$usersList['uid'].'"class="form-checkbox"  type="checkbox" '.$personChkVal.'>
              </div>
              </td><td>'.(($usersList['name']!="")?$usersList['name']:"").'</td><td>'.(($last_name_staff!="")?$last_name_staff:"").'</td>
              <td>'.(($usersList['mail']!="")?$usersList['mail']:"").'</td><td>'.(($cell_phone!="")?$cell_phone:"").'</td></tr>';
            }
      }

  }



   $form['personConductingContent']=array('#markup'=>$usersRow,

   '#default_value' => $item->personConductingContent,

    );

   $form['personConductingEnd']=array('#markup'=>'</tbody></table></div>');
       if(isset($item->startdatetime) && $item->startdatetime!=''){
    $startdatetime=$item->startdatetime;
}

$form['startdatetime'] = array(
  '#markup' => '<div class="capacity_view_details1"><h5>Start date</h5><p>'.$startdatetime.'</p></div>',
   '#default_value' => $item->startdatetime,
  );

    if(isset($item->enddatetime) && $item->enddatetime!=''){
    $enddatetime=$item->enddatetime;
}

$form['enddatetime'] = array(
  '#markup' => '<div class="capacity_view_details1"><h5>End date</h5><p>'.$enddatetime.'</p></div>',
   '#default_value' => $item->enddatetime,
  );

    if(isset($item->Length_of_services) && $item->Length_of_services!=''){
    $Length_of_services=$item->Length_of_services;
}
$form['Length_of_services'] = array(
  '#markup' => '<div class="capacity_view_details1"><h5>Length of services</h5><p>'.$Length_of_services.'</p></div>',
   '#default_value' => $item->Length_of_services,
  );
    if(isset($item->location) && $item->location!=''){
    $location=$item->location;
}

$form['location'] = array(
  '#markup' => '<div class="capacity_view_details1"><h5>Location</h5><p>'.$location.'</p></div>',
   '#default_value' => $item->location,
   '#prefix' => '<hr/>',
  );

   /* if(isset($item->Country) && $item->Country!=''){
    $Country=$item->Country;
    }
    $form['Country'] = array(
     '#markup' => '<div class="capacity_view_details1"><h5>Country</h5><p>United states</p></div>',
    );*/

    if(isset($item->address_1) && $item->address_1!=''){
    $address_1=$item->address_1;
}
$form['address_1'] = array(
  '#markup' => '<div class="capacity_view_details1"><h5>Address 1 </h5><p class="">'.$address_1.'</p></div>',
   '#default_value' => $item->address_1,
  );
    if(isset($item->address_2) && $item->address_2!=''){
    $address_2=$item->address_2;
}
$form['address_2'] = array(
  '#markup' => '<div class="capacity_view_details1"><h5>Address 2 </h5><p class="">'.$address_2.'</p></div>',
  );

    if(isset($item->city) && $item->city!=''){
    $city=$item->city;
}

      $form['city'] =array(
     '#markup' => '<div class="capacity_view_details1"><h5>City</h5><p>'.$city.'</p></div>',
  );

    if(isset($item->states) && $item->states!=''){
    $states=$item->states;
}
      $form['states'] =array(
     '#markup' => '<div class="capacity_view_details1"><h5>States</h5><p>'.$states.'</p></div>',
  );

    if(isset($item->zip_code) && $item->zip_code!=''){
    $zip_code=$item->zip_code;
}
      $form['zip_code'] =array(
     '#markup' => '<div class="capacity_view_details1"><h5>Zip code</h5><p>'.$zip_code.'</p></div>',
  );


    if(isset($item->number_adult_served) && $item->number_adult_served!=''){
    $number_adult_served=$item->number_adult_served;
}

     $form['number_adult_served'] =array(
     '#markup' => '<div class="capacity_view_details1"><h5>Number of adult served</h5><p>'.$number_adult_served.'</p></div>',
	 '#prefix' => '<hr/>',
  );

    if(isset($item->number_youth_served) && $item->number_youth_served!=''){
    $number_youth_served=$item->number_youth_served;
}
     $form['number_youth_served'] =array(
     '#markup' => '<div class="capacity_view_details1"><h5>Number of youth served</h5><p>'.$number_youth_served.'</p></div>',
  );
   if(isset($item->Number_Business_Attending) && $item->Number_Business_Attending!=''){
    $number_business_attending=$item->Number_Business_Attending;
}
     $form['Number_Business_Attending'] =array(
     '#markup' => '<div class="capacity_view_details1"><h5>Number business attending</h5><p>'.$number_business_attending.'</p></div>',
  );
       if(isset($item->description_of_purpose) && $item->description_of_purpose!=''){
    $description_of_purpose=$item->description_of_purpose;
}

     $form['description_of_purpose'] =array(
     '#markup' => '<div class="capacity_view_details1"><h5>Description of purpose</h5><p class="">'.$description_of_purpose.'</p></div>',
  );
       if(isset($item->description_of_outcome) && $item->description_of_outcome!=''){
    $description_of_outcome=$item->description_of_outcome;
}
    $form['description_of_outcome'] =array(
     '#markup' => '<div class="capacity_view_details1"><h5>Description of outcome</h5><p class="">'.$description_of_outcome.'</p></div>',
  );



// prerson conducting activities

   if(isset($item->Members_Invloved)){
    $members_id_arr=unserialize($item->Members_Invloved);
   }
  //echo "<pre>";print_r($item);die;
   $form['membersInvolvedStart']=array('#markup'=>'<div class="responsive_table"><h5>Members Involved</h5><table id="membersInvolvedTab" class="sticky-enabled table-select-processed">
 <thead><tr><th>First Name</th><th>Last Name</th><th>Email</th><th>Cell phone</th><th>Company organization</th> </tr></thead>
<tbody>');

  $membersRow='';
  foreach($all_user_details as $membersList){ //echo "<pre>";print_r($membersList);die;


      if($membersList['uid']!="0" && $membersList['roles'][7]!="Staff User"){


        $last_name_staff = db_query("SELECT field_last_name_value FROM field_data_field_last_name WHERE entity_id =".$membersList['uid'])->fetchField();//echo $last_name_staff."<pre>";print_r($usersList);die;


        $cell_phone = db_query("SELECT field_cell_phone_value FROM field_data_field_cell_phone WHERE entity_id =".$membersList['uid'])->fetchField();

        $org_name = db_query("SELECT field_company_organization_value FROM field_data_field_company_organization WHERE entity_id =".$membersList['uid'])->fetchField();


        if(in_array($membersList['uid'],$members_id_arr['Members_Invloved'])){
        $memChkVal=(in_array($membersList['uid'],$members_id_arr['Members_Invloved']))?'checked="checked"':'';

        $membersRow.='<tr class="odd"><td class="Member-hide" style="display:none"><div class="form-item form-type-checkbox form-item-person-conducting-0">
                <input id="edit-person-conducting-0" name="Members_Invloved[]" value="'.$membersList['uid'].'" class="form-checkbox" type="checkbox" '.$memChkVal.'>
              </div>
              </td><td>'.$membersList['name'].'</td><td>'.(($last_name_staff!="")?$last_name_staff:"").'</td><td>'.$membersList['mail'].'</td>
              <td>'.(($cell_phone!="")?$cell_phone:"").'</td><td>'.(($org_name!="")?$org_name:"").'</td></tr>';
            }
      }

  }


   $form['Members_Invloved']=array('#markup'=>$membersRow);

   $form['membersInvolvedEnd']=array('#markup'=>'</tbody></table></div>');

   if(isset($item->contactContent)){
        $contact_id_arr=unserialize($item->contactContent);
   }

   $form['contact_starts'] = array(
       '#markup' => "<div id='person_Conducting_changehidden'>"
   );
   $form['personContact'] = array(
       '#markup' => '<div class="responsive_table"> <label style="color:green;">Contact Lists <span class="form-required" title="This field is required.">*</span></label><table id="capContactListTab" class="sticky-enabled table-select-processed">
 <thead><tr><th>First Name</th><th>Last Name</th><th>Email</th><th>Phone</th><th>Company Organization</th><th>Primary Sector</th></tr></thead>
 <tbody>'
   );
   $contact_lists =db_query("SELECT * from {estar_contacts_details}")->fetchAll();
   $usersRow = '';
  if(isset($contact_lists) && count($contact_lists)>0){
   foreach ($contact_lists as $usersList)
   { //echo "<pre>";print_r($all_user_details);die;
       if (isset($usersList) && $usersList!="")
       {
         if(isset($usersList->primary_sector_select) && $usersList->primary_sector_select!=''){
              $primary_sector=get_taxonomy_term_name($usersList->primary_sector_select);
         }
         if(in_array($usersList->contact_id,$contact_id_arr['contact_list'])){

           $usersRow .= '<tr class="odd"><td>' . (($usersList->first_name != "") ? $usersList->first_name : "") . '</td>
             <td>' . (($usersList->last_name != "") ? $usersList->last_name : "") . '</td>
             <td>' . (($usersList->email != "") ? $usersList->email : "") . '</td>
             <td>' . (($usersList->phone != "") ? $usersList->phone : "") . '</td>
             <td>' . (($usersList->organization != "") ? $usersList->organization : "") . '</td>
             <td>' . (($primary_sector != "") ? $primary_sector : "") . '</td></tr>';
       }
     }

   }
 }else{
   $usersRow='<tr><td colspan="6">Contacts list is empty.</td></tr>';
 }


   $form['personContactContent'] = array(
       '#markup' => $usersRow,
   );

   $form['personContactEnd'] = array(
       '#markup' => '</tbody></table></div>'
   );
   $form['person_Contact_end'] = array(
       '#markup' => '</div>'
   );



if(isset($item->Donation_select) && $item->Donation_select!=''){
    $Donation_select_id=$item->Donation_select;
}

$Donation_data = unserialize($Donation_select_id);

if(isset($item->Monetary_Value) && $item->Monetary_Value!=''){
    $Monetary_Value_id=$item->Monetary_Value;
}

$Monetary_Value_data = unserialize($Monetary_Value_id);

if(isset($item->Comment) && $item->Comment!=''){
    $Comment_id=$item->Comment;
}

$Comment_data = unserialize($Comment_id);

if(isset($Donation_data['Donation_select']) && count($Donation_data['Donation_select'])>0){

$donation_view_data="";

foreach ($Donation_data['Donation_select'] as $key => $value){
	    $donation_view_data.="<tr><td>".$value."</td>";
	    $donation_view_data.="<td>".$Monetary_Value_data['Monetary_Value'][$key]."</td>";
	    $donation_view_data.="<td>".$Comment_data['Comment'][$key]."</td><tr>";

}
}

//print_r($Donation_data);die();
$form['Donation1'] = array(
'#markup' => '<div class="responsive_table"><h5>Donation</h5><table id="myTable" class=" table order-list">
    <thead>
        <tr>
            <th>Donation</th>
            <th>Monetary Value</th>
            <th>Comment</th>
        </tr>
    </thead>
    <tbody>
    '.$donation_view_data.'
    </tbody>
    </table></div>
'
);


if(isset($item->Attachments_fid) && $item->Attachments_fid!=''){
	$upload_ids=unserialize($item->Attachments_fid);

$form['Attachments-title'] = array(
  '#markup' => ''
  );



$form['Attachments_files'] = array(
  '#prefix' => '<div class="responsive_table"><h5>Attachment</h5>
    <table id="myTable2" class=" table order-list-att">
      <tr><th>' . t('Attachments') . '</th><th>' . t('Comments') . '</tr></th>'.'<tr><td class="table_heading">
    ',
);

if(isset($upload_ids['upload_id']) && count($upload_ids['upload_id'])>0){

	foreach($upload_ids['upload_id'] as $uploadId){
		$fid=$uploadId;
		$file_upload_details = db_query("SELECT * FROM {file_managed} WHERE fid = ".$fid)->fetchAll();

		$fURI=$file_upload_details[0]->uri;
		$fname=$file_upload_details[0]->filename;
		$fileURI=file_create_url($fURI);

		if($fname!=""){

			$form['Attachments_fid'.$uploadId] =  array(
				'#markup' => t('<div class="upload_data"><a href='.$fileURI.'> <i class="fa fa-cloud-download" aria-hidden="true"></i> '.$fname.'</a> </div>'),
		    );
       }
   }

}

    if(isset($item->Attachments_notes) && $item->Attachments_notes!=''){
		$Attachments_notes=$item->Attachments_notes;
	}
$form['Attachments_notes'] = array(
  '#markup' => '<td class="col-sm-3">'.$Attachments_notes.'</td></tr>
        </table>  </div>
    ',
);

}//echo "<pre>";print_r($upload_ids);die;
   /* $form['signature'] = array(
        '#type' => 'checkboxes',
       '#title' => t('Signature'),
       '#options' => array('signature'=>"I certify that the information above is true, accurate and correct to the best of my knowledge. "),
       '#required'=>TRUE,
       '#default_value' => $item->signature,
        '#attributes' => array('checked' => 'checked','disabled'=>'disabled'),
   );*/

    $form['signature'] = array(
        '#type' => 'radios',
       '#title' => t('Signature'),
       '#options' => array('yes'=>"Pending",'1'=>"I certify that the information above is true, accurate and correct to the best of my knowledge. "),
       '#required'=>TRUE,
       '#default_value' => ($item->signature=="0" || $item->signature=="2")?$item->is_pending:$item->signature,
        '#attributes' => array('disabled'=>'disabled'),
   );

   //$capacity_info = db_query("SELECT created_uid,created_at,updated_at,updated_uid FROM {capacity_details_info} WHERE capacity_id=".$item->capacity_id." GROUP BY updated_uid")->fetchAll();

   $capacity_info=db_query("SELECT created_uid,created_at,updated_at,updated_uid
FROM capacity_details_info
WHERE capacity_id=".$item->capacity_id)->fetchAll();

      $created_by_img = file_create_url(path_to_theme().'/images/businessman.png');

   $capacity_creator_info = db_query("SELECT created_uid,created_at FROM {capacity_details_info} WHERE capacity_id=".$item->capacity_id." AND created_at IS NOT NULL")->fetchAll();
   //echo "<pre>";print_r($capacity_info);die;

   if(isset($capacity_creator_info) && count($capacity_creator_info)>0){
    if(isset($capacity_creator_info[0]->created_uid) && $capacity_creator_info[0]->created_uid!=""){
				$user=user_load($capacity_creator_info[0]->created_uid);
				$creator_name=$user->name;
			   $form['revisons_create_details']=array(
					'#markup'=>'<div class="user_create_section"><div class="user-det create_user_section"><div class="image_section"><img src='.$created_by_img.' class="white_img"></div><div class="content_section"><h5>Created by:</h5> <p>'.$creator_name.'</p></div></div>
								<div class="user-date-det create_user_section"><div class="image_section"><img src='.$created_by_img.' class="white_img"></div><div class="content_section"><h5>Created on: </h5> <p>'.$capacity_creator_info[0]->created_at.'</p></div></div></div>',
			   );
	  }
    }

  if(isset($capacity_info) && count($capacity_info)>0){
   foreach($capacity_info as $cap_key=> $capacity_data){

	   /*if(isset($capacity_data->created_uid) && $capacity_data->created_uid!=""){
				$user=user_load($capacity_data->created_uid);
				$creator_name=$user->name;
			   $form['revisons_create_details']=array(
					'#markup'=>'<div class="user_create_section"><div class="user-det create_user_section"><div class="image_section"><img src='.$created_by_img.' class="white_img"></div><div class="content_section"><h5>Created by:</h5> <p>'.$creator_name.'</p></div></div>
								<div class="user-date-det create_user_section"><div class="image_section"><img src='.$created_by_img.' class="white_img"></div><div class="content_section"><h5>Created on: </h5> <p>'.$capacity_data->created_at.'</p></div></div></div>',
			   );
	  }*/
	  if(isset($capacity_data->updated_uid) && $capacity_data->updated_uid!=""){
				$user=user_load($capacity_data->updated_uid);
				$updator_name=$user->name;

			   $form['revisons_update_details'.$cap_key]=array(
					'#markup'=>'<div class="user_edit_section"><div class="user-det create_user_section"><div class="image_section"><img src='.$created_by_img.' class="white_img"></div><div class="content_section"><h5>Edited by:</h5> <p>'.$updator_name.'</p></div></div>
								<div class="user-date-det create_user_section"><div class="image_section"><img src='.$created_by_img.' class="white_img"></div><div class="content_section"><h5>Edited on: </h5> <p>'.$capacity_data->updated_at.'</p></div></div></div>',
			   );
	   }
    }
   }

  return $form;
}


function capacity_edit_item_form($form, &$form_state, $item)
{
	global $user;
// Add CSS and JS files, add some markup

  //$html = 'scripts[] = misc/jquery.js';
    //$form = array();
    //$form['#tree'] = TRUE;
    $form['#attributes']['enctype'] = 'multipart/form-data';

    $base_url=$GLOBALS['base_url'];

    drupal_set_title("Capacity Edit Page");

  //$form['#item'] = $item;

    $contributing_factor = db_query("SELECT tid, name FROM {taxonomy_term_data} WHERE vid = 12")->fetchAll();

    $interventions = db_query("SELECT tid, name FROM {taxonomy_term_data} WHERE vid = 28")->fetchAll();


  //$planning_lists = db_query("SELECT planning_id, title FROM {planning_details}")->fetchAll();
      $query = db_select('planning_details','a');
      $query->fields('a', array('planning_id','title'));
      $query->orderBy('a.title','ASC');
      $planning_lists = $query->execute()->fetchAll();
  $planCount=0;$lmCount=0;
      foreach($planning_lists as $plankey=>$planVal){
    $plan_id=$planVal->planning_id;
    $plan_title=$planVal->title;
    $planning_data_lists = db_query("SELECT * FROM {planning_details} WHERE planning_id = ".$plan_id)->fetchAll();
    //echo "<pre>";print_r($planning_data_lists);die;

    $chkSerialize = @unserialize($planning_data_lists[0]->contributing_factor);
    if ($chkSerialize !== false) {
      $contributingFactor=unserialize($planning_data_lists[0]->contributing_factor);
        $interventionsCheckedItems=unserialize($planning_data_lists[0]->interventions);
        $logicModelCount=count($contributingFactor['contributingCollection']);
        //echo $logicModelCount."<pre>";print_r($contributingFactor);echo "<pre>";print_r($interventionsCheckedItems);die;
      $conSelectedItems="";$intSelectedItems="";
    //$contributingItems="";
     $contributingItems='<div id="firstTable_'.$plankey.'" class="heading_tag">
							<h3>'.$plan_title.'</h3>
							<div class="select_btn">
								<div class="form-checkboxes">
									<div class="form-item form-type-checkbox">
										<label><input id="checkAllLogicModel" type="checkbox" value="" class="form-checkbox" name="contributing_factor" onchange="checkAllFunc(this,'.$planCount.')"> Select all/Select none</label>
									</div>
								</div>
							</div>
						</div>
	<div class="logicmodel_inter_con" id="logicmodel_inter_con_'.$planCount.'">';
     $planCount++;
       $unCFValues=unserialize($item->contributing_factor_models);
       $unINValues=unserialize($item->intervention_models);
      $ico=1;//echo $logicModelCount;die;
       for($i=0;$i<$logicModelCount;$i++){
        $ichange=$plankey.'_'.$i;

        $contributingItems.='<div class="capacity_logic_section"><div id="conFactorTable_'.$i.'" class="conFactorTab">
                           <div class="form-type-checkboxes"><label class="heading_label">Contributing Factor</label>';
      foreach($contributing_factor as $fKey=>$fVal){
          if($fVal->name==trim($contributingFactor['contributingCollection']['contribCollection'.$i])){
			  $cfCheck=($unCFValues['contributing_factor']['contributing_factor'.$ichange]==$fVal->tid)?'checked':'';
            $contributingItems.='<div class="form-checkboxes">
                      <div class="form-item form-type-checkbox"><label><input type="checkbox" value="'.$fVal->tid.'" class="form-checkbox" name="contributing_factor'.$ichange.'" '.$cfCheck.'><span> '.$fVal->name.'</span></label></div>
                      </div>';
          }

      }
      $contributingItems.='</div></div>
      <div id="intervTable_'.$i.'" class="interventions intervTab">
          <div class="form-type-checkboxes"><label class="heading_label">Interventions</label>
      ';

      foreach($interventions as $cKey=>$cVal){
           if(in_array($cVal->name,$interventionsCheckedItems['interventionCollection']['internCollection'.$i])){
			   $inCheck=(in_array($cVal->tid,$unINValues['interventions']['interventions'.$ichange]) && $cfCheck)?'checked':'';
            $contributingItems.='<div class="form-checkboxes">
                                <div class="form-item form-type-checkbox"><label><input type="checkbox" value="'.$cVal->tid.'" class="form-checkbox" name="interventions'.$ichange.'[]" '.$inCheck.'><span> '.$cVal->name.'</span></label></div>
                     </div>';
           }

      }

      $contributingItems.='</div></div></div>';

      //$contributingItems.='</table>';

        #--------------------------------------
        # create a "planning logic model" fieldset
        #--------------------------------------
        $form['planningLogicModel'.$plankey] = array(
        '#type' => 'fieldset',
        '#title' => t($plan_title),
        '#collapsible' => TRUE,
        '#collapsed' => ($plankey=="0")?FALSE:TRUE,
        );

      $ico++;


}

  $contributingItems.='</div></table>';
    $form['planningLogicModel'.$plankey]['contributing_intervention'.$plankey] =array(
    "#title"  => 'Logic model',
    "#markup"=> $contributingItems
    );

    $form['table_count_id']=array(
      '#type'=>"hidden",
      '#value'=>($logicModelCount-1),
      '#attributes'=>array("id"=>"LogicModelCountId")
    );


        //echo "<pre>";print_r($contributingFactor);echo "<pre>";print_r($interventionsCheckedItems);die;
    } else {

      $contributingFactor=$planning_data_lists[0]->contributing_factor;
      $interventionsCheckedItems=explode(",",$planning_data_lists[0]->interventions);

      $ichange=$plankey.'_'.$lmCount;
       $unCFValues=unserialize($item->contributing_factor_models);
       $unINValues=unserialize($item->intervention_models);

      $contributingItems="";
    foreach($contributing_factor as $fKey=>$fVal){
        if($contributingFactor==$fVal->name){
			$cfCheck=($unCFValues['contributing_factor']['contributing_factor'.$ichange]==$fVal->tid)?'checked':'';
          $contributingItems.='<div class="form-checkboxes">
                                <div class="form-item form-type-checkbox"><label><input type="checkbox" value="'.$fVal->tid.'" class="form-checkbox" name="contributing_factor'.$ichange.'" '.$cfCheck.'><span> '.$fVal->name.' </span><label></div>
                  </div>';
        }
    }

    $interventionsItems="";
    foreach($interventions as $cKey=>$cVal){ //echo $cVal."<pre>";print_r($interventionsCheckedItems);die;
         if(in_array($cVal->name,$interventionsCheckedItems)){
			 $inCheck=(in_array($cVal->tid,$unINValues['interventions']['interventions'.$ichange]))?'checked':'';
          $interventionsItems.='<div class="form-checkboxes">
                                <div class="form-item form-type-checkbox"><label><input type="checkbox" value="'.$cVal->tid.'" class="form-checkbox" name="interventions'.$ichange.'[]" '.$inCheck.'><span> '.$cVal->name.'</span><label></div>
                    </div>';
         }
    }
        #--------------------------------------
        # create a "planning logic model" fieldset
        #--------------------------------------
        $form['planningLogicModel'.$plankey] = array(
        '#type' => 'fieldset',
        '#title' => t($plan_title),
        '#collapsible' => TRUE,
        '#collapsed' => ($plankey=="0")?FALSE:TRUE,
        );

    $form['planningLogicModel'.$plankey]['contributing_intervention'.$plankey] =array(
    "#title"  => 'Logic model',
      "#markup"=> '
      <div id="firstTable'.$plankey.'" class="heading_tag">
			<h3>'.$plan_title.'</h3>
			<div class="select_btn">
				<div class="form-checkboxes">
					<div class="form-item form-type-checkbox">
						<label><input id="checkAllLogicModel" type="checkbox" value="" name="contributing_factor" class="form-checkbox" onchange="checkAllFunc(this,'.$planCount.')"> Select all/Select none</label>
					</div>
				</div>
			</div>
		</div>
 <div class="logicmodel_inter_con" id="logicmodel_inter_con_'.$planCount.'">
           <div class="capacity_logic_section">
               <div id="conFactorTab" class="conFactorTab">
					<div class="form-type-checkboxes">
						<label class="heading_label">Contributing Factor</label>
                            '.$contributingItems.'
                     </div>
				</div>
                <div id="intervTab" class="interventions intervTab">
					<div class="form-type-checkboxes">
						<label class="heading_label">Interventions</label>
                           '.$interventionsItems.'
                   </div>
				</div>
            </div>
        </div>
</table>');

    $form['table_count_id']=array(
      '#type'=>"hidden",
      '#value'=>0,
      '#attributes'=>array("id"=>"LogicModelCountId")
    );

    $planCount++;
    $lmCount++;

    }

}


//csap 6 fields Information Dissemination
if(isset($item->Record_meeting) && $item->Record_meeting!=""){
  $form['Record'] = array(
  '#prefix'=>'<div class="select_section capacity_select_Section record_selection">',
	'#suffix'=>'</div>',
    '#type' => 'select',
   '#title' => t('Type'),
    '#options' => array('Title of Meeting Event'=>"Record Meeting",'Title of Training/Technical Assistance Event'=>"Record Training/Technical Assistance"),
      '#default_value' => $item->Record,
  );
}

if(isset($item->Record_tranning) && $item->Record_tranning!=""){
  $form['Record'] = array(
  '#prefix'=>'<div class="select_section capacity_select_Section record_selection">',
	'#suffix'=>'</div>',
    '#type' => 'select',
   '#title' => t('Type'),
    '#options' => array('Title of Meeting Event'=>"Record Meeting",'Title of Training/Technical Assistance Event'=>"Record Training/Technical Assistance"),
      '#default_value' => $item->Record,
  );
}
//echo $item->Record_meeting;die;
//csap 6 fields Information Dissemination

  $form['Record_meeting'] = array(
    '#type' => 'textfield',
   '#title' => t('Title of Meeting Event'),
    '#default_value' => $item->Record_meeting,
'#states' => array(
    'visible' => array(
        ':input[name="Record"]' => array(
            array('value' => t('Title of Meeting Event')),
        ),
    ),
  ),
  );


  $form['Record_tranning'] = array(
    '#type' => 'textfield',
   '#title' => t('Title of Training/Technical Assistance Event'),
   '#default_value' => $item->Record_tranning,

'#states' => array(
    'visible' => array(
        ':input[name="Record"]' => array(
            array('value' => t('Title of Training/Technical Assistance Event')),

        ),
    ),
),
  );


$all_user_lists = entity_load('user');

$all_user_details = json_decode(json_encode($all_user_lists), true);




   if(isset($item->personConductingContent)){
    $personConduct_id_arr=unserialize($item->personConductingContent);
   }
   //echo "<pre>";print_r($item);die;


   $form['personConducting']=array('#markup'=>'<div class="responsive_table"><label>Person Conducting</label><table id="personConductingTab" class="sticky-enabled table-select-processed">
 <thead><tr><th class="select-all"><input id="conSelectAll" class="form-checkbox" title="Select all rows in this table" type="checkbox"></th><th>First Name</th><th>Last Name</th><th>Email</th><th>Cell phone</th> </tr></thead>
<tbody>');
  $usersRow='';
  foreach($all_user_details as $usersList){ //echo "<pre>";print_r($usersList);die;
      if($usersList['uid']!="0" && isset($usersList['roles'][7]) && $usersList['roles'][7]=="Staff User"){

        $last_name_staff = db_query("SELECT field_last_name_value FROM field_data_field_last_name WHERE entity_id =".$usersList['uid'])->fetchField();
        $cell_phone = db_query("SELECT field_cell_phone_value FROM field_data_field_cell_phone WHERE entity_id =".$usersList['uid'])->fetchField();
        $personChkVal=(in_array($usersList['uid'],$personConduct_id_arr['person_conducting']))?'checked="checked"':'';
        $usersRow.='<tr class="odd"><td><div class="form-item form-type-checkbox form-item-person-conducting-0">
                <input id="edit-person-conducting-0" name="person_conducting[]" value="'.$usersList['uid'].'" class="form-checkbox" type="checkbox" '.$personChkVal.'>
              </div>
              </td><td>'.(($usersList['name']!="")?$usersList['name']:"").'</td><td>'.(($last_name_staff!="")?$last_name_staff:"").'</td>
              <td>'.(($usersList['mail']!="")?$usersList['mail']:"").'</td><td>'.(($cell_phone!="")?$cell_phone:"").'</td></tr>';
      }

  }



   $form['personConductingContent']=array('#markup'=>$usersRow,

   '#default_value' => $item->personConductingContent,

    );

   $form['personConductingEnd']=array('#markup'=>'</tbody></table></div>');

$form['startdatetime'] = array(
      '#type' => 'date_popup',
      '#title' => 'Start Date',
      '#timepicker' => 'timepicker',
      '#date_format' => 'Y-m-d H:i A',
      '#timepicker_options' => array(
        'rows' => 6,
        'minutes' => array(
          'starts' => 0,
          'ends' => 56,
          'interval' => 5,
        ),
        'showCloseButton' => TRUE,
        'closeButtonText' => t('Close'),
        'showPeriod'=> true,
        'showLeadingZero'=> true,
        'showNowButton'=> true,
        'showDeselectButton'=> true,
      ),
      '#default_value' => $item->startdatetime,
     );

  $form['end_date_wrapper'] = array
  (
    '#prefix' => '<div id="end_date_wrapper">',
    '#suffix' => '</div>',
    '#markup' => '',
  );

    $form['enddatetime'] = array(
      '#type' => 'date_popup',
      '#title' => 'End Date',
      '#timepicker' => 'timepicker',
      '#date_format' => 'Y-m-d H:i A',
      '#timepicker_options' => array(
        'rows' => 6,
        'minutes' => array(
          'starts' => 0,
          'ends' => 56,
          'interval' => 5,
        ),
        'showCloseButton' => TRUE,
        'closeButtonText' => t('Close'),
        'showPeriod'=> true,
        'showLeadingZero'=> true,
        'showNowButton'=> true,
        'showDeselectButton'=> true,
      ),
      '#default_value' => $item->enddatetime,
     );



    $form['Length_of_services'] =array(
       '#type' => 'textfield',
       '#title' => 'Length of Service (in minutes)',
       '#default_value' => $item->Length_of_services,
    );


    $form['location'] =array(
       '#type' => 'textfield',
       '#title' => 'Location',
		'#default_value' => $item->location,
		 '#prefix'=>'<hr/>',
    );



    /*$form['Country'] = array(
      '#prefix'=>'<div class="select_section capacity_select_Section">',
		'#suffix'=>'</div>',
        '#type' => 'select',
        '#title' => t('country') ,

        '#options' => array(
        'United State' => "United State",
        ) ,
         '#default_value' => $item->Country,
    );*/

    $form['address_1'] = array(
        '#type' => 'textfield',
        '#title' => t('Address 1') ,
         '#default_value' => $item->address_1,

    );
    $form['address_2'] = array(
        '#type' => 'textfield',
        '#title' => t('Address 2') ,
          '#default_value' => $item->address_2,
    );
      $form['city'] =array(
       '#type' => 'textfield',
       '#title' => 'City',
      '#default_value' => $item->city,
    );


$form['states'] = array(
'#prefix'=>'<div class="select_section capacity_select_Section">',
		'#suffix'=>'</div>',
'#type' => 'select',
'#title' => t('State') ,
'#options' => get_state_lists(),
   '#default_value' => $item->states,
);


   $form['zip_code'] = array(
        '#type' => 'textfield',
        '#title' => t('zip Code') ,
            '#default_value' => $item->zip_code,
              '#suffix' => '</table>', // Don't forget to close the table rows, and finally the table.
    );


$form['number_adult_served'] = array(
  '#type' => 'textfield',
  '#title' => t('Number of Adult served') ,
  '#maxlength' => 10,
  '#size' => 3,
  '#default_value' => $item->number_adult_served,
  '#prefix'=>'<hr/>',
);
$form['number_youth_served'] = array(
  '#type' => 'textfield',
  '#title' => t('Number of youth served') ,
  '#maxlength' => 10,
  '#size' => 3,
  '#default_value' => $item->number_adult_served,
);
$form['number_business_attending'] = array(
  '#type' => 'textfield',
   '#title' => t('Number of business attending') ,
  '#maxlength' => 10,
  '#size' => 3,
  '#default_value' => $item->Number_Business_Attending,
);


$form['description_of_purpose'] = array(
       '#type' => 'textarea',
       '#title' => t('Description of Purpose'),
       '#required'=>TRUE,
        '#default_value' => $item->description_of_purpose,
		'#prefix'=>'<hr/>',
  );


$form['description_of_outcome'] = array(
       '#type' => 'textarea',
       '#title' => t('Description of Outcome'),
       '#required'=>TRUE,
       '#default_value' => $item->description_of_outcome,
  );



// prerson conducting activities

   if(isset($item->Members_Invloved)){
    $members_id_arr=unserialize($item->Members_Invloved);
   }
  //echo "<pre>";print_r($item);die;
   $form['membersInvolvedStart']=array('#markup'=>'<div class="responsive_table"><label>Members Involved</label><table id="membersInvolvedTab" class="sticky-enabled table-select-processed">
 <thead><tr><th class="select-all"><input id="memSelectAll" class="form-checkbox" title="Select all rows in this table" type="checkbox"></th><th>First Name</th><th>Last Name</th><th>Email</th><th>Cell phone</th><th>Company organization</th> </tr></thead>
<tbody>');
  $membersRow='';
  foreach($all_user_details as $membersList){
      if($membersList['uid']!="0" && $membersList['roles'][7]!="Staff User"){
        $last_name_staff = db_query("SELECT field_last_name_value FROM field_data_field_last_name WHERE entity_id =".$membersList['uid'])->fetchField();//echo $last_name_staff."<pre>";print_r($usersList);die;
        $cell_phone = db_query("SELECT field_cell_phone_value FROM field_data_field_cell_phone WHERE entity_id =".$membersList['uid'])->fetchField();
        $org_name = db_query("SELECT field_company_organization_value FROM field_data_field_company_organization WHERE entity_id =".$membersList['uid'])->fetchField();
        $memChkVal=(in_array($membersList['uid'],$members_id_arr['Members_Invloved']))?'checked="checked"':'';
        $membersRow.='<tr class="odd"><td><div class="form-item form-type-checkbox form-item-person-conducting-0">
                <input id="edit-person-conducting-0" name="Members_Invloved[]" value="'.$membersList['uid'].'" class="form-checkbox" type="checkbox" '.$memChkVal.'>
              </div>
              </td><td>'.$membersList['name'].'</td><td>'.(($last_name_staff!="")?$last_name_staff:"").'</td><td>'.$membersList['mail'].'</td>
              <td>'.(($cell_phone!="")?$cell_phone:"").'</td><td>'.(($org_name!="")?$org_name:"").'</td></tr>';
      }

  }

   $form['Members_Invloved']=array('#markup'=>$membersRow);

   $form['membersInvolvedEnd']=array('#markup'=>'</tbody></table></div>');

   if(isset($item->contactContent)){
        $contact_id_arr=unserialize($item->contactContent);
   }

   $form['contact_starts'] = array(
       '#markup' => "<div id='person_Conducting_changehidden'>"
   );
   $form['personContact'] = array(
       '#markup' => '<div class="responsive_table"> <label style="color:green;">Contact Lists <span class="form-required" title="This field is required.">*</span></label><table id="capContactListTab" class="sticky-enabled table-select-processed">
 <thead><tr><th class="select-all"><input id="capContactSelectAll" class="form-checkbox" title="Select all rows in this table" type="checkbox"></th><th>First Name</th><th>Last Name</th><th>Email</th><th>Phone</th><th>Company Organization</th><th>Primary Sector</th></tr></thead>
 <tbody>'
   );
   $contact_lists =db_query("SELECT * from {estar_contacts_details}")->fetchAll();
   $usersRow = '';
  if(isset($contact_lists) && count($contact_lists)>0){
   foreach ($contact_lists as $usersList)
   { //echo "<pre>";print_r($all_user_details);die;
       if (isset($usersList) && $usersList!="")
       {
         if(isset($usersList->primary_sector_select) && $usersList->primary_sector_select!=''){
              $primary_sector=get_taxonomy_term_name($usersList->primary_sector_select);
         }
           $contChkVal=(in_array($usersList->contact_id,$contact_id_arr['contact_list']))?'checked="checked"':'';
           $usersRow .= '<tr class="odd"><td><div class="form-item form-type-checkbox form-item-person-conducting-0">
               <label><input id="teamManagerId" name="contact_person_conducting[]" value="' . $usersList->contact_id. '" class="form-checkbox required " type="checkbox" title="contact" '.$contChkVal.'></label>

             </td><td>' . (($usersList->first_name != "") ? $usersList->first_name : "") . '</td>
             <td>' . (($usersList->last_name != "") ? $usersList->last_name : "") . '</td>
             <td>' . (($usersList->email != "") ? $usersList->email : "") . '</td>
             <td>' . (($usersList->phone != "") ? $usersList->phone : "") . '</td>
             <td>' . (($usersList->organization != "") ? $usersList->organization : "") . '</td>
             <td>' . (($primary_sector != "") ? $primary_sector : "") . '</td></tr>';
       }

   }
 }else{
   $usersRow='<tr><td colspan="6">Contacts list is empty.</td></tr>';
 }


   $form['personContactContent'] = array(
       '#markup' => $usersRow,
   );

   $form['personContactEnd'] = array(
       '#markup' => '</tbody></table></div>'
   );
   $form['person_Contact_end'] = array(
       '#markup' => '</div>'
   );


if(isset($item->Donation_select) && $item->Donation_select!=''){
    $Donation_select_id=$item->Donation_select;
}

if(isset($item->Monetary_Value) && $item->Monetary_Value!=''){
    $Monetary_Value_id=$item->Monetary_Value;
}

if(isset($item->Comment) && $item->Comment!=''){
    $Comment_id=$item->Comment;
}


$Donation_data = unserialize($Donation_select_id);

$Monetary_Value_data = unserialize($Monetary_Value_id);

$Comment_data = unserialize($Comment_id);

//echo "<pre>";print_r($Monetary_Value_data);die;
$donation_data="";
if(isset($Donation_data['Donation_select']) && count($Donation_data['Donation_select'])>0){
foreach ($Donation_data['Donation_select'] as $key => $value) {

$donation_data.='<tr>
					<td class="table_heading">
						<div id="remove-Donation'.$key.'" class="new_data">
							<div class="remove-edit'.$key.'" >
								<div class="select_section capacity_select_Section">
									 <select name="Donation_select['.$key.']" id="edit-'.$key.'" class="form-select">
										 <option value="Materials" '.(($value=="Materials")?"selected=selected":"").'>Materials</option>
										 <option value="Food and refreshments" '.(($value=="Food and refreshments")?"selected=selected":"").'>Food and refreshments</option>
										 <option value="Marketing" '.(($value=="Marketing")?"selected=selected":"").'>Marketing</option>
										 <option value="Support" '.(($value=="Support")?"selected=selected":"").'>Support</option>
									 </select>
								</div>
							</div>
						</div>
					</td>';

$donation_data.='<td class="table_heading">
					<div id="remove-Monetary'.$key.'">
						<div class="remove-edit'.$key.'">
							<input name="Monetary_Value['.$key.']" id="edit-'.$key.'" value="'.$Monetary_Value_data['Monetary_Value'][$key].'" size="60" maxlength="128" class="form-text" type="text">
						</div>
					</div>
				</td>';

$donation_data.='<td class="table_heading">
					<div id="remove-Comment'.$key.'" class="remove-edit'.$key.'">
						<div class="form-item form-type-textarea form-item-'.$key.'">
							<div class="form-textarea-wrapper resizable textarea-processed resizable-textarea">
								<textarea name="Comment['.$key.']" id="edit-'.$key.'" cols="60" rows="5" class="form-textarea">'.$Comment_data['Comment'][$key].'</textarea>
							</div>
						</div>
					</div>
				</td>';
$donation_data.='<td class="table_heading">
					<div  class="button button_remove">
						<input type="button" id="remove-edit'.$key.'" class="remove-edit btn-danger" onclick="donation(this,'.$key.')" value="Remove">
					</div>
				</td>
			</tr>';

}
}

$form['Donation1'] = array(
'#markup' => '<div class="responsive_table"><label>Donation</label><table id="myTableedit" class=" table order-list-edit">
    <thead>
        <tr>
            <th>Donation</th>
            <th>Monetary Value</th>
            <th>Comment</th>
            <th>Operation</th>
        </tr>
    </thead>
    <tbody>
'.$donation_data.'
    </tbody>
    </table>
'
);


$form['donatio_table'] = array(
 '#markup' => '</tbody></table></div>
    <div id="addrowedit" class="button button_addmore"><input type="button" class="btn btn-lg btn-block add_more_btn"  value="Add More field" /></div>',
  );

if(isset($item->Attachments_fid) && $item->Attachments_fid!=''){
	$upload_ids=unserialize($item->Attachments_fid);
}//echo "<pre>";print_r($upload_ids);die;



$form['Attachments-title'] = array(
  '#markup' => ''
  );


$form['Attachments_files'] = array(
  '#prefix' => '<div class="responsive_table"><label>Attachment</label>
    <table id="myTable2" class="table order-list-att">
      <tr><th>' . t('Attachments') . '</th><th>' . t('Comments') . '</th></tr>'.'<tr><td class="table_heading">
    ',
);

if(isset($upload_ids['upload_id']) && count($upload_ids['upload_id'])>0){

	foreach($upload_ids['upload_id'] as $uploadId){
		$fid=$uploadId;
		$file_upload_details = db_query("SELECT * FROM {file_managed} WHERE fid = ".$fid)->fetchAll();

		$fURI=$file_upload_details[0]->uri;
		$fname=$file_upload_details[0]->filename;
		$fileURI=file_create_url($fURI);
		if($fname!=""){
				$form['Attachments_fid'.$uploadId] =  array(
					'#markup' => t('<div class="upload_data"><a href='.$fileURI.'><i class="fa fa-cloud-download" aria-hidden="true"></i>
 '.$fname.'</a></div>'),
			   );
        }
   }

}

$form['Attachments_fid'] =  array(
    '#type' => 'managed_file_multiple',
    '#title' => 'Upload files',
    '#upload_validators' => array('file_validate_extensions' => array('doc docx jpg pdf png ppt pptx txt xls xlsx ')),
    '#upload_location' => 'public://capacity_documents/',
    '#description' => t('<br>Please use the Choose file button to attach a response document<br><strong>Allowed extensions: doc docx jpg pdf png ppt pptx txt xls xlsx</strong>.'),
	'#prefix' => '<tr><td class="table_heading">',
    '#suffix' => '</td>',
  );
$form['Attachments_notes'] = array(
  '#prefix' => '<td class="table_heading">',
  '#type' => 'textarea',
    '#rows' => 5,
    '#cols' => 30,
  '#suffix' => '</td></tr>
        </table></div>
    <td colspan="5" style="text-align: left;">
                <input style="display:none;" type="button" class="btn btn-lg btn-block " id="addrow-list" value="Add More field" />
            </td>
    ', // Don't forget to close the table rows, and finally the table.
      '#default_value' => $item->Attachments_notes,
);

    /*$form['signature'] = array(
        '#type' => 'checkboxes',
       '#title' => t('Signature'),
       '#options' => array('1'=>"I certify that the information above is true, accurate and correct to the best of my knowledge. "),
       '#required'=>TRUE,
   );*/

   if(isset($item->signature) && $item->signature=="2"){
        $sig_fields=array(
                     '0'=>"Pending",
                     '2' => "Save a Copy/Add a Component",
                     '1'=>"I certify that the information above is true, accurate and correct to the best of my knowledge.");
        $form['save_and_copy']=array(
                        '#type'=>"hidden",
                        '#value'=>"Save and Copy",
        );

   }else{
        $sig_fields=array('0'=>"Pending",'1'=>"I certify that the information above is true, accurate and correct to the best of my knowledge. ");
   }

   $form['signature'] = array(
        '#type' => 'radios',
       '#title' => t('Signature'),
       '#options' => $sig_fields,
       '#required'=>TRUE,
       '#default_value' => ($item->signature=="0" || $item->signature=="2")?$item->is_pending:$item->signature,
   );

      $form['attachment_upload_id']=array(
      '#type'=>"hidden",
      '#value'=>$item->Attachments_fid,
    );


   $form['capacity_id']=array(
      '#type'=>"hidden",
      '#value'=>$item->capacity_id,
    );

     $form['updated_time'] = array(
      '#type' => 'hidden',
      '#title' => 'Start Date',
      '#value' => date('m-d-Y h:i:s a'),
     );

     $form['created_user_id'] = array(
      '#type' => 'hidden',
      '#title' => 'Creator Id',
      '#value' => $item->created_uid,
     );

     $form['updated_user_id'] = array(
      '#type' => 'hidden',
      '#title' => 'Updator Id',
      '#value' => $user->uid,
     );

    /* if(isset($item->created_uid) && $item->created_uid!=""){
			$user=user_load($item->created_uid);
			$creator_name=$user->name;
			$created_by_img1 = file_create_url(path_to_theme().'/images/businessman.png');

		   $form['revisons_create_details']=array(
				'#markup'=>'<div class="user_create_section"><div class="user-det create_user_section"><div class="image_section"><img src='.$created_by_img1.' class="white_img"></div><div class="content_section"><h5>Created by: </h5> <p>'.$creator_name.'</p></div></div>
							<div class="user-date-det create_user_section"><div class="image_section"><img src='.$created_by_img1.' class="white_img"></div><div class="content_section"><h5>Created on:  </h5> <p>'.$item->created_at.'</p></div></div></div>',
		   );
	  }
	  if(isset($item->updated_uid) && $item->updated_uid!=""){
				$user=user_load($item->updated_uid);
				$updator_name=$user->name;

			   $form['revisons_update_details']=array(
					'#markup'=>'<div class="user_edit_section"><div class="user-det create_user_section"><div class="image_section"><img src='.$created_by_img1.' class="white_img"></div><div class="content_section"><h5>Edited by: </h5> <p>'.$updator_name.'</p></div></div>
								<div class="user-date-det create_user_section"><div class="image_section"><img src='.$created_by_img1.' class="white_img"></div><div class="content_section"><h5>Edited on: </h5> <p>'.$item->updated_at.'</p></div></div></div>',
			   );
	   }*/

	      //$capacity_info = db_query("SELECT created_uid,created_at,updated_at,updated_uid FROM {capacity_details_info} WHERE capacity_id=".$item->capacity_id." GROUP BY updated_uid")->fetchAll();

	         $capacity_info=db_query("SELECT created_uid,created_at,updated_at,updated_uid
									FROM capacity_details_info
									WHERE capacity_id=".$item->capacity_id)->fetchAll();

   $created_by_img = file_create_url(path_to_theme().'/images/businessman.png');

   $capacity_creator_info = db_query("SELECT created_uid,created_at FROM {capacity_details_info} WHERE capacity_id=".$item->capacity_id." AND created_at IS NOT NULL")->fetchAll();
   //echo "<pre>";print_r($capacity_creator_info);die;

   if(isset($capacity_creator_info) && count($capacity_creator_info)>0){
    if(isset($capacity_creator_info[0]->created_uid) && $capacity_creator_info[0]->created_uid!=""){
				$user=user_load($capacity_creator_info[0]->created_uid);
				$creator_name=$user->name;
			   $form['revisons_create_details']=array(
					'#markup'=>'<div class="user_create_section"><div class="user-det create_user_section"><div class="image_section"><img src='.$created_by_img.' class="white_img"></div><div class="content_section"><h5>Created by:</h5> <p>'.$creator_name.'</p></div></div>
								<div class="user-date-det create_user_section"><div class="image_section"><img src='.$created_by_img.' class="white_img"></div><div class="content_section"><h5>Created on: </h5> <p>'.$capacity_creator_info[0]->created_at.'</p></div></div></div>',
			   );
	  }
    }

  if(isset($capacity_info) && count($capacity_info)>0){
   foreach($capacity_info as $cap_key=> $capacity_data){

	  /* if(isset($capacity_data->created_uid) && $capacity_data->created_uid!=""){
				$user=user_load($capacity_data->created_uid);
				$creator_name=$user->name;
			   $form['revisons_create_details']=array(
					'#markup'=>'<div class="user_create_section"><div class="user-det create_user_section"><div class="image_section"><img src='.$created_by_img.' class="white_img"></div><div class="content_section"><h5>Created by:</h5> <p>'.$creator_name.'</p></div></div>
								<div class="user-date-det create_user_section"><div class="image_section"><img src='.$created_by_img.' class="white_img"></div><div class="content_section"><h5>Created on: </h5> <p>'.$capacity_data->created_at.'</p></div></div></div>',
			   );
	  }*/
	  if(isset($capacity_data->updated_uid) && $capacity_data->updated_uid!=""){
				$user=user_load($capacity_data->updated_uid);
				$updator_name=$user->name;

			   $form['revisons_update_details'.$cap_key]=array(
					'#markup'=>'<div class="user_edit_section"><div class="user-det create_user_section"><div class="image_section"><img src='.$created_by_img.' class="white_img"></div><div class="content_section"><h5>Edited by:</h5> <p>'.$updator_name.'</p></div></div>
								<div class="user-date-det create_user_section"><div class="image_section"><img src='.$created_by_img.' class="white_img"></div><div class="content_section"><h5>Edited on: </h5> <p>'.$capacity_data->updated_at.'</p></div></div></div>',
			   );
	   }
    }
   }




	$form['next_btn_div_start']=array('#markup'=>"<div class='assessment-nxt-btn capacity-btn '>");
  $form['submit'] = array
  (
    '#type' => 'submit',
    '#value' => t('Update'),
  );
  $form['next_btn_div_end']=array('#markup'=>"</div>");

  //$capId=$item->capacity_id;
  //$form['#action'][]=$base_url."/capacitycontent/$capId/view";

  return $form;
}






function capacity_item_form($form, &$form_state, $item)
{

	global $user;
// Add CSS and JS files, add some markup

  //$html = 'scripts[] = misc/jquery.js';
    $form = array();
    $form['#tree'] = TRUE;
    $form['#attributes']['enctype'] = 'multipart/form-data';

    $base_url=$GLOBALS['base_url'];

    drupal_set_title("Capacity Add Page");

  //$form['#item'] = $item;

    $contributing_factor = db_query("SELECT tid, name FROM {taxonomy_term_data} WHERE vid = 12")->fetchAll();

    $interventions = db_query("SELECT tid, name FROM {taxonomy_term_data} WHERE vid = 28")->fetchAll();


  //$planning_lists = db_query("SELECT planning_id, title FROM {planning_details}")->fetchAll();
      $query = db_select('planning_details','a');
      $query->fields('a', array('planning_id','title'));
      $query->orderBy('a.title','ASC');
      $planning_lists = $query->execute()->fetchAll();
  $planCount=0;$lmCount=0;
      foreach($planning_lists as $plankey=>$planVal){
    $plan_id=$planVal->planning_id;
    $plan_title=$planVal->title;
    $planning_data_lists = db_query("SELECT * FROM {planning_details} WHERE planning_id = ".$plan_id)->fetchAll();
    //echo "<pre>";print_r($planning_data_lists);die;

    $chkSerialize = @unserialize($planning_data_lists[0]->contributing_factor);
    if ($chkSerialize !== false) {
      $contributingFactor=unserialize($planning_data_lists[0]->contributing_factor);
        $interventionsCheckedItems=unserialize($planning_data_lists[0]->interventions);
        $logicModelCount=count($contributingFactor['contributingCollection']);
        //echo $logicModelCount."<pre>";print_r($contributingFactor);echo "<pre>";print_r($interventionsCheckedItems);die;
      $conSelectedItems="";$intSelectedItems="";
    //$contributingItems="";
     $contributingItems='<div id="firstTable_'.$plankey.'" class="heading_tag">
		<h3>'.$plan_title.'</h3>
			<div class="select_btn">
				<div class="form-checkboxes">
					<div class="form-item form-type-checkbox"><label><input id="checkAllLogicModel" type="checkbox" class="form-checkbox" value="" name="contributing_factor" onchange="checkAllFunc(this,'.$planCount.')"> Select all/Select none</label>
					</div>
				</div>
			</div>
	 </div>
	 <div class="logicmodel_inter_con" id="logicmodel_inter_con_'.$planCount.'">';
     $planCount++;
      $ico=1;//echo $logicModelCount;die;
       for($i=0;$i<$logicModelCount;$i++){
        /*if($i=="0"){
			$ichange="";
          }else{
			$ichange=$i;
		  }*/
		$ichange=$plankey.'_'.$i;


        $contributingItems.='<div class="capacity_logic_section"><div id="conFactorTable_'.$i.'" class="conFactorTab">
								<div class="form-type-checkboxes"><label class="heading_label">Contributing Factor</label>';
      foreach($contributing_factor as $fKey=>$fVal){
          if($fVal->name==trim($contributingFactor['contributingCollection']['contribCollection'.$i])){
            $contributingItems.='<div class="form-checkboxes">
                                <div class="form-item form-type-checkbox"><label><input type="checkbox" value="'.$fVal->tid.'" class="form-checkbox" name="contributing_factor'.$ichange.'"><span> '.$fVal->name.'</span></label></div>
                     </div>';
          }

      }
      $contributingItems.='</div></div>
      <div id="intervTable_'.$i.'" class="interventions intervTab">
                            <div class="form-type-checkboxes"><label class="heading_label">Interventions</label>

      ';

      foreach($interventions as $cKey=>$cVal){
           if(in_array($cVal->name,$interventionsCheckedItems['interventionCollection']['internCollection'.$i])){
            $contributingItems.='<div class="form-checkboxes">
                                <div class="form-item form-type-checkbox"><label><input type="checkbox" value="'.$cVal->tid.'" class="form-checkbox" name="interventions'.$ichange.'[]"><span> '.$cVal->name.'</span></label></div>
                     </div>';
           }

      }

      $contributingItems.='</div></div></div>';

      //$contributingItems.='</table>';

        #--------------------------------------
        # create a "planning logic model" fieldset
        #--------------------------------------
        $form['planningLogicModel'.$plankey] = array(
        '#type' => 'fieldset',
        '#title' => t($plan_title),
        '#collapsible' => TRUE,
        '#collapsed' => ($plankey=="0")?FALSE:TRUE,
        '#attributes' => array('class'=>array("planning-fieldset")),
        );

      $ico++;


}

  $contributingItems.='</div></table>';
    $form['planningLogicModel'.$plankey]['contributing_intervention'.$plankey] =array(
    "#title"  => 'Logic model',
    "#markup"=> $contributingItems
    );

    $form['table_count_id']=array(
      '#type'=>"hidden",
      '#value'=>($logicModelCount-1),
      '#attributes'=>array("id"=>"LogicModelCountId")
    );


        //echo "<pre>";print_r($contributingFactor);echo "<pre>";print_r($interventionsCheckedItems);die;
    } else {//echo $lmCount;die;
      $ichange=$plankey.'_'.$lmCount;
      $contributingFactor=$planning_data_lists[0]->contributing_factor;
      $interventionsCheckedItems=explode(",",$planning_data_lists[0]->interventions);

      $contributingItems="";
    foreach($contributing_factor as $fKey=>$fVal){
        if($contributingFactor==$fVal->name){
          $contributingItems.='<div class="form-checkboxes">
                                <div class="form-item form-type-checkbox"><label><input type="checkbox" value="'.$fVal->tid.'" class="form-checkbox" name="contributing_factor'.$ichange.'"><span> '.$fVal->name.'</span><label></div>
                   </div>';
        }
    }

    $interventionsItems="";
    foreach($interventions as $cKey=>$cVal){ //echo $cVal."<pre>";print_r($interventionsCheckedItems);die;
         if(in_array($cVal->name,$interventionsCheckedItems)){
          $interventionsItems.='<div class="form-checkboxes">
                                <div class="form-item form-type-checkbox"><label><input type="checkbox" value="'.$cVal->tid.'" class="form-checkbox" name="interventions'.$ichange.'[]"><span> '.$cVal->name.'</span><label></div>
                   </div>';
         }
    }

        $form['planningLogicModel'.$plankey] = array(
        '#type' => 'fieldset',
        '#title' => t($plan_title),
        '#collapsible' => TRUE,
        '#collapsed' => ($plankey=="0")?FALSE:TRUE,
        '#attributes' => array('class'=>array("planning-fieldset")),
        );

    $form['planningLogicModel'.$plankey]['contributing_intervention'.$plankey] =array(
    "#title"  => 'Logic model',
      "#markup"=> '
		<div id="firstTable'.$plankey.'" class="heading_tag">
			<h3>'.$plan_title.'</h3>
			<div class="select_btn">
				<div class="form-checkboxes">
					<div class="form-item form-type-checkbox">
						<label><input id="checkAllLogicModel" type="checkbox" value="" name="contributing_factor" class="form-checkbox" onchange="checkAllFunc(this,'.$planCount.')"> Select all/Select none</label>
					</div>
				</div>
			</div>
		</div>
		<div class="logicmodel_inter_con" id="logicmodel_inter_con_'.$planCount.'">
           <div class="capacity_logic_section">
               <div id="conFactorTab" class="conFactorTab">
					<div class="form-type-checkboxes">
						<label class="heading_label">Contributing Factor</label>
						'.$contributingItems.'
					</div>
				</div>
				<div id="intervTab" class="interventions intervTab">
					<div class="form-type-checkboxes">
						<label class="heading_label">Interventions</label>
						'.$interventionsItems.'
					</div>
				</div>
            </div>
        </div>
</table>');

    $form['table_count_id']=array(
      '#type'=>"hidden",
      '#value'=>0,
      '#attributes'=>array("id"=>"LogicModelCountId")
    );

    $planCount++;
    $lmCount++;

    }

}



//csap 6 fields Information Dissemination
  $form['Record'] = array(
	'#prefix'=>'<div class="select_section capacity_select_Section record_selection">',
	'#suffix'=>'</div>',
    '#type' => 'select',
   '#title' => t('Type'),
   '#required'=>TRUE,
    '#options' => array('Title of Meeting Event'=>"Record Meeting",'Title of Training/Technical Assistance Event'=>"Record Training/Technical Assistance"),
      '#default_value' => (isset($_REQUEST['type']) && $_REQUEST['type']=="meeting")?"Title of Meeting Event":"Title of Training/Technical Assistance",
  );


//csap 6 fields Information Dissemination
  $form['Record_meeting'] = array(
    '#type' => 'textfield',
   '#title' => t('Title of Meeting Event'),
   //'#required'=>TRUE,
    '#default_value' => $item->Record_meeting,
'#states' => array(
    'visible' => array(
        ':input[name="Record"]' => array(
            array('value' => t('Title of Meeting Event')),
        ),
    ),
  ),
  );

  $form['Record_tranning'] = array(
    '#type' => 'textfield',
   '#title' => t('Title of Training/Technical Assistance Event'),
   '#default_value' => $item->Record_tranning,

'#states' => array(
    'visible' => array(
        ':input[name="Record"]' => array(
            array('value' => t('Title of Training/Technical Assistance Event')),

        ),
    ),
),
  );

$all_user_lists = entity_load('user');

$all_user_details = json_decode(json_encode($all_user_lists), true);




   if(isset($item->personConductingContent)){
    $personConduct_id_arr=unserialize($item->personConductingContent);
   }
   //echo "<pre>";print_r($personConduct_id_arr);die;


   $form['personConducting']=array('#markup'=>'<div class="responsive_table"> <label>Person Conducting</label><table id="personConductingTab" class="sticky-enabled table-select-processed">
 <thead><tr><th class="select-all"><input id="conSelectAll" class="form-checkbox" title="Select all rows in this table" type="checkbox"></th><th>First Name</th><th>Last Name</th><th>Email</th><th>Cell phone</th> </tr></thead>
<tbody>');
  $usersRow='';
  foreach($all_user_details as $usersList){ //echo "<pre>";print_r($usersList);die;
      if($usersList['uid']!="0" && isset($usersList['roles'][7]) && $usersList['roles'][7]=="Staff User"){

        $last_name_staff = db_query("SELECT field_last_name_value FROM field_data_field_last_name WHERE entity_id =".$usersList['uid'])->fetchField();
        $cell_phone = db_query("SELECT field_cell_phone_value FROM field_data_field_cell_phone WHERE entity_id =".$usersList['uid'])->fetchField();
        $personChkVal=(in_array($usersList['uid'],$personConduct_id_arr['person_conducting']))?'checked="checked"':'';
        $usersRow.='<tr class="odd"><td><div class="form-item form-type-checkbox form-item-person-conducting-0">
                <label><input id="edit-person-conducting-0" name="person_conducting[]" value="'.$usersList['uid'].'" class="form-checkbox" type="checkbox" '.$personChkVal.'></label>
              </div>
              </td><td>'.(($usersList['name']!="")?$usersList['name']:"").'</td><td>'.(($last_name_staff!="")?$last_name_staff:"").'</td>
              <td>'.(($usersList['mail']!="")?$usersList['mail']:"").'</td><td>'.(($cell_phone!="")?$cell_phone:"").'</td></tr>';
      }

  }



   $form['personConductingContent']=array('#markup'=>$usersRow,

   '#default_value' => $item->personConductingContent,

    );

   $form['personConductingEnd']=array('#markup'=>'</tbody></table></div>');


$form['startdatetime'] = array(
      '#type' => 'date_popup',
      '#title' => 'Start Date',
    '#timepicker' => 'timepicker',
    '#date_format' => 'Y-m-d H:i A',
    '#timepicker_options' => array(
      'rows' => 6,
      'minutes' => array(
        'starts' => 0,
        'ends' => 56,
        'interval' => 5,
      ),
      'showCloseButton' => TRUE,
      'closeButtonText' => t('Close'),
      'showPeriod'=> true,
      'showLeadingZero'=> true,
      'showNowButton'=> true,
      'showDeselectButton'=> true,
    ),
     );
  $form['end_date_wrapper'] = array
  (
    '#prefix' => '<div id="end_date_wrapper">',
    '#suffix' => '</div>',
    '#markup' => '',
  );

    $form['enddatetime'] = array(
      '#type' => 'date_popup',
      '#title' => 'End Date',
      '#timepicker' => 'timepicker',
      '#date_format' => 'Y-m-d H:i A',
      '#timepicker_options' => array(
        'rows' => 6,
        'minutes' => array(
          'starts' => 0,
          'ends' => 56,
          'interval' => 5,
        ),
        'showCloseButton' => TRUE,
        'closeButtonText' => t('Close'),
        'showPeriod'=> true,
        'showLeadingZero'=> true,
        'showNowButton'=> true,
        'showDeselectButton'=> true,
      ),
     );


    $form['Length_of_services'] =array(
       '#type' => 'textfield',
       '#title' => 'Length of Service (in minutes)',
	     '#required'=>TRUE,
       '#default_value' => $item->Length_of_services,
    );


    $form['location'] =array(
       '#type' => 'textfield',
       '#title' => 'Location',
   '#default_value' => $item->location,
   '#prefix' => '<hr/>',
    );

    $form['address_1'] = array(
        '#type' => 'textfield',
        '#title' => t('Address 1') ,
         '#default_value' => $item->address_1,
    );
    $form['address_2'] = array(
        '#type' => 'textfield',
        '#title' => t('Address 2') ,
          '#default_value' => $item->address_2,
    );
      $form['city'] =array(
       '#type' => 'textfield',
       '#title' => 'City',
      '#default_value' => $item->city,
    );


$form['states'] = array(
'#prefix'=>'<div class="select_section capacity_select_Section">',
		'#suffix'=>'</div>',
'#title' => t('states') ,
'#type' => 'select',
'#options' => get_state_lists(),
   '#default_value' => $item->states,
);


   $form['zip_code'] = array(
        '#type' => 'textfield',
        '#title' => t('zip Code') ,
		  '#element_validate' => array('element_validate_number'),
		    '#maxlength' => 6,
            '#default_value' => $item->zip_code,
              '#suffix' => '</table>', // Don't forget to close the table rows, and finally the table.
    );


$form['number_adult_served'] = array(
  '#type' => 'textfield',
  '#title' => t('Number of Adult served') ,
  '#maxlength' => 10,
  '#size' => 3,
       '#default_value' => $item->number_adult_served,
	   '#prefix' => '<hr/>',
);
$form['number_youth_served'] = array(
  '#type' => 'textfield',
  '#title' => t('Number of youth served') ,
  '#maxlength' => 10,
  '#size' => 3,
  '#default_value' => $item->number_adult_served,
);
$form['number_business_attending'] = array(
  '#type' => 'textfield',
   '#title' => t('Number of business attending') ,
  '#maxlength' => 10,
  '#size' => 3,
  '#default_value' => $item->Number_Business_Attending,
);


$form['description_of_purpose'] = array(
       '#type' => 'textarea',
       '#title' => t('Description of Purpose'),
       '#required'=>TRUE,
        '#default_value' => $item->description_of_purpose,
		'#prefix' => '<hr/>',
  );


$form['description_of_outcome'] = array(
       '#type' => 'textarea',
       '#title' => t('Description of Outcome'),
       '#required'=>TRUE,
       '#default_value' => $item->description_of_outcome,
  );



// prerson conducting activities

   if(isset($item->Members_Invloved)){
    $members_id_arr=unserialize($item->Members_Invloved);
   }
  //echo "<pre>";print_r($item);die;
   $form['membersInvolvedStart']=array('#markup'=>'<div class="responsive_table"><label>Members Involved</label><table id="membersInvolvedTab" class="sticky-enabled table-select-processed">
 <thead><tr><th class="select-all"><input id="memSelectAll" class="form-checkbox" title="Select all rows in this table" type="checkbox"></th><th>First Name</th><th>Last Name</th><th>Email</th><th>Cell phone</th><th>Company organization</th> </tr></thead>
<tbody>');
  $membersRow='';
  foreach($all_user_details as $membersList){ //echo "<pre>";print_r($membersList);die;
      if($membersList['uid']!="0" && $membersList['roles'][7]!="Staff User"){
        $last_name_staff = db_query("SELECT field_last_name_value FROM field_data_field_last_name WHERE entity_id =".$membersList['uid'])->fetchField();//echo $last_name_staff."<pre>";print_r($usersList);die;
        $cell_phone = db_query("SELECT field_cell_phone_value FROM field_data_field_cell_phone WHERE entity_id =".$membersList['uid'])->fetchField();
        $org_name = db_query("SELECT field_company_organization_value FROM field_data_field_company_organization WHERE entity_id =".$membersList['uid'])->fetchField();
        $memChkVal=(in_array($membersList['uid'],$members_id_arr['Members_Invloved']))?'checked="checked"':'';
        $membersRow.='<tr class="odd"><td><div class="form-item form-type-checkbox form-item-person-conducting-0">
                <input id="edit-person-conducting-0" name="Members_Invloved[]" value="'.$membersList['uid'].'" class="form-checkbox" type="checkbox" '.$memChkVal.'>
              </div>
              </td><td>'.$membersList['name'].'</td><td>'.(($last_name_staff!="")?$last_name_staff:"").'</td><td>'.$membersList['mail'].'</td>
              <td>'.(($cell_phone!="")?$cell_phone:"").'</td><td>'.(($org_name!="")?$org_name:"").'</td></tr>';
      }

  }

   $form['Members_Invloved']=array('#markup'=>$membersRow);

   $form['membersInvolvedEnd']=array('#markup'=>'</tbody></table></div>');


   $form['contact_starts'] = array(
       '#markup' => "<div id='person_Conducting_changehidden'>"
   );
   $form['personContact'] = array(
       '#markup' => '<div class="responsive_table"> <label style="color:green;">Contact Lists <span class="form-required" title="This field is required.">*</span></label><table id="capContactListTab" class="sticky-enabled table-select-processed">
 <thead><tr><th class="select-all"><input id="capContactSelectAll" class="form-checkbox" title="Select all rows in this table" type="checkbox"></th><th>First Name</th><th>Last Name</th><th>Email</th><th>Phone</th><th>Company Organization</th><th>Primary Sector</th></tr></thead>
 <tbody>'
   );
   $contact_lists =db_query("SELECT * from {estar_contacts_details}")->fetchAll();
   $usersRow = '';
  if(isset($contact_lists) && count($contact_lists)>0){
   foreach ($contact_lists as $usersList)
   { //echo "<pre>";print_r($all_user_details);die;
       if (isset($usersList) && $usersList!="")
       {
         if(isset($usersList->primary_sector_select) && $usersList->primary_sector_select!=''){
              $primary_sector=get_taxonomy_term_name($usersList->primary_sector_select);
         }
           $usersRow .= '<tr class="odd"><td><div class="form-item form-type-checkbox form-item-person-conducting-0">
               <label><input id="teamManagerId" name="contact_person_conducting[]" value="' . $usersList->contact_id. '" class="form-checkbox required " type="checkbox" title="contact"></label>

             </td><td>' . (($usersList->first_name != "") ? $usersList->first_name : "") . '</td>
             <td>' . (($usersList->last_name != "") ? $usersList->last_name : "") . '</td>
             <td>' . (($usersList->email != "") ? $usersList->email : "") . '</td>
             <td>' . (($usersList->phone != "") ? $usersList->phone : "") . '</td>
             <td>' . (($usersList->organization != "") ? $usersList->organization : "") . '</td>
             <td>' . (($primary_sector != "") ? $primary_sector : "") . '</td></tr>';
       }

   }
 }else{
   $usersRow='<tr><td colspan="6">Contacts list is empty.</td></tr>';
 }


   $form['personContactContent'] = array(
       '#markup' => $usersRow,
   );

   $form['personContactEnd'] = array(
       '#markup' => '</tbody></table></div>'
   );
   $form['person_Contact_end'] = array(
       '#markup' => '</div>'
   );



$form['Donation1'] = array(
'#markup' => '<div class="responsive_table"><table id="myTable" class=" table order-list">
    <thead>
        <tr>
            <td>Donation</td>
            <td>Monetary Value</td>
            <td>Comment</td>
			<td class="table_remove_title">Remove</td>
        </tr>
    </thead>
    <tbody>
'
);


$form['Title-donation'] = array(
  '#markup' => '<label>Donation </label>'
  );

$form['Donation_select']['0'] = array(

'#type' => 'select',

'#options' => array('Materials'=>"Materials", 'Food and refreshments'=>"Food and refreshments", 'Marketing'=>"Marketing",'Support'=>"Support"),
'#prefix' => '<tr>
<td class="table_heading"><div class="select_section capacity_select_Section">',
   '#default_value' => $item->Donation_select,
   '#suffix' => '</div></td>
    ',
);


$form['Monetary_Value']['0']= array(
  '#prefix' => '  <td class="table_heading">',
  '#type' => 'textfield',
  '#maxlength' => 10,
  '#size' => 10,
  '#suffix' => '</td>
    ',
       '#default_value' => $item->Monetary_Value,
);

if(isset($item->Attachments_fid) && $item->Attachments_fid!=''){
    $fid=$item->Attachments_fid;
    $file_upload_details = db_query("SELECT * FROM {file_managed} WHERE fid = ".$fid)->fetchAll();
    //echo "<pre>";print_r($file_upload_details);die;
    $fURI=$file_upload_details[0]->uri;
    $fname=$file_upload_details[0]->filename;
    $fileURI=file_create_url($fURI);

}
$form['Comment']['0']= array(
  '#prefix' => '<td class="table_heading">',
  '#type' => 'textarea',
    '#rows' => 5,
    '#cols' => 30,
  '#suffix' => '</td></tr>
        </table></div>

				<div id="addrow" class="button button_addmore">
                <input type="button" class="btn btn-lg btn-block add_more_btn"  value="Add More field" />
				</div>

    ', // Don't forget to close the table rows, and finally the table.
      '#default_value' => $item->Comment,
);



  $form['hidden_field']=array(
      '#type'=>"hidden",
      '#value'=>"0",
      '#attributes' => array('name'=>'[0]'),
      '#attributes'=>array("id"=>"hidden_id")
    );


$form['Attachments-title'] = array(
  '#markup' => '<label>Attachment</label>'
  );




$form['Attachments_files'] = array(
  '#prefix' => '<div class="responsive_table">
    <table id="myTable2" class="table order-list-att">
      <tr><th>' . t('Attachments') . '</th><th>' . t('Comments') . '</th><th class="table_remove_title1">Remove</th></tr>'.'<tr><td class="table_heading">
    ',
);
$form['Attachments_fid'] =  array(
  '#type' => 'managed_file_multiple',
   '#title' => 'Managed file field',
    '#upload_validators' => array('file_validate_extensions' => array('doc docx jpg pdf png ppt pptx txt xls xlsx')),
    '#upload_location' => 'public://capacity_documents/',
      '#description' => t('<a href='.$fileURI.'> '.$fname.'</a> <br>Please use the Choose file button to attach a response document<br><strong>Allowed extensions: doc docx jpg pdf png ppt pptx txt xls xlsx</strong>.'),
'#prefix' => '<tr>
<td class="table_heading">',
   '#suffix' => '</td>
    ',
  );


$form['Attachments_notes'] = array(
  '#prefix' => '<td class="table_heading">',
  '#type' => 'textarea',
    '#rows' => 5,
    '#cols' => 30,
  '#suffix' => '</td></tr>
        </table></div>
    <td colspan="5" style="text-align: left;">
			<div class="button button_addmore" style="display:none;">
                <input  type="button" class="btn btn-lg btn-block " id="addrow-list" value="Add More field" />
			</div>
            </td>
    ', // Don't forget to close the table rows, and finally the table.
      '#default_value' => $item->Attachments_notes,
);
   /* $form['signature'] = array(
        '#type' => 'checkboxes',
       '#title' => t('Signature'),
       '#options' => array('1'=>"I certify that the information above is true, accurate and correct to the best of my knowledge. "),
       '#required'=>TRUE,
   );*/

      $form['signature'] = array(
        '#type' => 'radios',
       '#title' => t('Signature'),
       '#options' => array(
                    '0'=>"Pending",
                    '2' => "Save a Copy/Add a Component",
                    '1'=>"I certify that the information above is true, accurate and correct to the best of my knowledge."),
       '#required'=>TRUE,
   );

      $form['attachment_upload_id']=array(
      '#type'=>"hidden",
      '#value'=>$item->Attachments_fid,
    );

    $form['created_time'] = array(
      '#type' => 'hidden',
      '#title' => 'Start Date',
      '#value' => date('m-d-Y h:i:s a'),
     );

     $form['user_id'] = array(
      '#type' => 'hidden',
      '#title' => 'User Id',
      '#value' => $user->uid,
     );


	$form['next_btn_div_start']=array('#markup'=>"<div class='assessment-nxt-btn capacity-btn '>");
	  $form['submit'] = array
	  (
		'#type' => 'submit',
		'#value' => t('Save'),
	  );
	 $form['next_btn_div_end']=array('#markup'=>"</div>");

  //$capId=$item->capacity_id;
  //$form['#action'][]=$base_url."/capacitycontent/$capId/view";

  return $form;
}

function  capacity_item_form_validate($form, &$form_state)  {
  $file1 = file_save_upload('file1');
  if (isset($file1)) {
    // File upload was attempted.
    if ($file1) {
      // The temporary file should be put in form_values so we can save it on submit.
      $form_state['values']['file1_upload'] = $file1;
    }
    else {
      // File upload failed.
      form_set_error('file1', t('The file cannot be uploaded.'));
    }
  }
}


function capacity_edit_item_form_submit($form, &$form_state)
{
  global $user;
	$query = db_select('planning_details','a');
      $query->fields('a', array('planning_id','title'));
      $query->orderBy('a.title','ASC');
      $planning_lists = $query->execute()->fetchAll();
	  $lmCount=0;
		  foreach($planning_lists as $plankey=>$planVal){
				$plan_id=$planVal->planning_id;
				$planning_data_lists = db_query("SELECT * FROM {planning_details} WHERE planning_id = ".$plan_id)->fetchAll();
			$chkSerialize = @unserialize($planning_data_lists[0]->contributing_factor);
			if ($chkSerialize !== false) {
				$contributingFactor=unserialize($planning_data_lists[0]->contributing_factor);
                $interventionsCheckedItems=unserialize($planning_data_lists[0]->interventions);
				$logicModelCount=count($contributingFactor['contributingCollection']);
				 for($i=0;$i<$logicModelCount;$i++){
					 if(isset($_REQUEST['contributing_factor'.$plankey.'_'.$i])){
						$cfLogicModels['contributing_factor'.$plankey.'_'.$i]=$_REQUEST['contributing_factor'.$plankey.'_'.$i];
				     }
					 for($inv=0;$inv<count($_REQUEST['interventions'.$plankey.'_'.$i]);$inv++){
						 if(isset($_REQUEST['interventions'.$plankey.'_'.$i])){
							$inLogicModels['interventions'.$plankey.'_'.$i]=$_REQUEST['interventions'.$plankey.'_'.$i];
					    }
				     }
				 }

			}else{
				   if(isset($_REQUEST['contributing_factor'.$plankey.'_'.$lmCount])){
				     $cfLogicModels['contributing_factor'.$plankey.'_'.$lmCount]=$_REQUEST['contributing_factor'.$plankey.'_'.$lmCount];
				   }
					 for($inv=0;$inv<count($_REQUEST['interventions'.$plankey.'_'.$lmCount]);$inv++){
						 if(isset($_REQUEST['interventions'.$plankey.'_'.$lmCount])){
							$inLogicModels['interventions'.$plankey.'_'.$lmCount]=$_REQUEST['interventions'.$plankey.'_'.$lmCount];
					     }
				     }
				$lmCount++;
			}

		  }//echo "<pre>";print_r($_REQUEST);die;
		  $conArrModels['contributing_factor']=$cfLogicModels;
		  $invArrModels['interventions']=$inLogicModels;

$person_conducting="";
if(count($_REQUEST['person_conducting'])>0){
for($i=0;$i<count($_REQUEST['person_conducting']);$i++){
 $person_conducting['person_conducting'][$i]=$_REQUEST['person_conducting'][$i];
}
}
$person_conductin_data=serialize($person_conducting);


$person_conducting="";
if(count($_REQUEST['person_conducting'])>0){
for($i=0;$i<count($_REQUEST['person_conducting']);$i++){
 $person_conducting['person_conducting'][$i]=$_REQUEST['person_conducting'][$i];
}
}
$person_conductin_data=serialize($person_conducting);




 /* $values = $form_state['values'];
  if ($file = $values['Attachments']) {
  unset($values['Attachments_upload']);
  $filename = file_unmanaged_copy($file->url);
 $values['Attachments'] = $filename;
 }
  variable_set('Attachments', $values['Attachments']);

  $item = $form['#item'];*/
  //echo "<pre>";print_r($_REQUEST);die;
  if(isset($_REQUEST['attachment_upload_id']) && $_REQUEST['attachment_upload_id']!=''){
		$already_upload_ids=unserialize($_REQUEST['attachment_upload_id']);

  }//echo count($already_upload_ids['upload_id'])."<pre>";print_r($already_upload_ids);die;

  if(isset($_REQUEST['Attachments_fid']['files']) && count($_REQUEST['Attachments_fid']['files'])>0){
	  if(isset($already_upload_ids['upload_id']) && count($already_upload_ids['upload_id'])>0) {
			$ui=count($already_upload_ids['upload_id']);
      }else{
			$ui=0;
	  }
	  foreach($_REQUEST['Attachments_fid']['files'] as $uploadId=>$uploadVal ){
			$file_upload_ids['upload_id'][$ui]=$uploadId;
			$ui++;
	  }
  }else{
	   $file_upload_ids['upload_id']=$file_upload_ids['upload_id'];
  }

  if(isset($already_upload_ids['upload_id']) && count($already_upload_ids['upload_id'])>0){
	$file_upload_ids['upload_id']=array_merge($already_upload_ids['upload_id'],$file_upload_ids['upload_id']);
  }else{
	$file_upload_ids['upload_id']=$file_upload_ids['upload_id'];
  }

  if(!isset($_REQUEST['Attachments_fid']['files'])){
		$file_upload_ids=$already_upload_ids;
  }


  //echo "<pre>";print_r($file_upload_ids);die;


$Members_Invloved="";
if(count($_REQUEST['Members_Invloved'])>0){
for($i=0;$i<count($_REQUEST['Members_Invloved']);$i++){
 $Members_Invloved['Members_Invloved'][$i]=$_REQUEST['Members_Invloved'][$i];
}
}
$members_invloved_data=serialize($Members_Invloved);

$contact_list="";
if(count($_REQUEST['contact_person_conducting'])>0){
for($i=0;$i<count($_REQUEST['contact_person_conducting']);$i++){
 $contact_list['contact_list'][$i]=$_REQUEST['contact_person_conducting'][$i];
}
}
$contact_list_data=serialize($contact_list);

$counts = $_REQUEST['hidden_field'];


$Donation_select=$Monetary_Value=$Comment=array();
if(count($_REQUEST['Donation_select'])>0){
$i = 0;
foreach ($_REQUEST['Donation_select'] as $keyz => $valuez) {
    $Donation_select['Donation_select'][$i]=$valuez;
    $Monetary_Value['Monetary_Value'][$i]=$_REQUEST['Monetary_Value'][$keyz];
    $Comment['Comment'][$i]=$_REQUEST['Comment'][$keyz];
    $i++;
  }
}
$Donation_select_data=serialize($Donation_select);
$Monetary_Value_data=serialize($Monetary_Value);
$Comment_data=serialize($Comment);


 //echo "<pre>";print_r($_REQUEST);die;

 if(isset($_REQUEST['save_and_copy']) && $_REQUEST['save_and_copy']=='Save and Copy')
   {

     if(isset($form_state['values']['Record_meeting']) && $form_state['values']['Record_meeting']!=''){
       $eventTitle=$form_state['values']['Record_meeting'];
     }else{
       $eventTitle=$form_state['values']['Record_tranning'];
     }
     $eventStartDate=$form_state['values']['startdatetime'];
     $eventEndDate=$form_state['values']['enddatetime'];
     $event_status=(isset($form_state['values']['signature']) && $form_state['values']['signature'] == "yes") ? "Pending" : "Completed";
     /* Calendar Event Creation */
     $event_node_id=create_data_event_node($eventTitle, $user->uid,$createdDate,$changedDate,$event_type="Capacity", $status="1",$eventStartDate,$eventEndDate,$event_status);


    $capacityId= db_insert('capacity_details')
     ->fields(array(
 	 'contributing_factor_models' => serialize($conArrModels),
       'intervention_models' => serialize($invArrModels),
       'Record' => $form_state['values']['Record'],
       'Record_meeting' => $form_state['values']['Record_meeting'],
       'Record_tranning' => $form_state['values']['Record_tranning'],
       'personConductingContent' => $person_conductin_data,
       'contactContent'=>$contact_list_data,
       'startdatetime' => $form_state['values']['startdatetime'],
       'enddatetime' => $form_state['values']['enddatetime'],
       'Length_of_services' => $form_state['values']['Length_of_services'],
       'location' => $form_state['values']['location'],
       'country' => $form_state['values']['Country'],
       'address_1' => $form_state['values']['address_1'],
       'address_2' => $form_state['values']['address_2'],
       'city' => $form_state['values']['city'],
       'states' => $form_state['values']['states'],
       'zip_code' => $form_state['values']['zip_code'],
       'number_adult_served' => $form_state['values']['number_adult_served'],
       'number_youth_served' => $form_state['values']['number_youth_served'],
       'number_business_attending' => $form_state['values']['number_business_attending'],
       'description_of_purpose' => $form_state['values']['description_of_purpose'],
       'description_of_outcome' => $form_state['values']['description_of_outcome'],
       'Members_Invloved' => $members_invloved_data,
       'Donation_select' => $Donation_select_data,
       'Monetary_Value' => $Monetary_Value_data,
       'Comment' => $Comment_data,
       'user_id'=>$user->uid,
       'Attachments_fid' => (isset($file_upload_ids) && count($file_upload_ids)>"0")?serialize($file_upload_ids):"",
       'Attachments_notes' => $form_state['values']['Attachments_notes'],
       'is_pending' => ($form_state['values']['signature']=="0" || $form_state['values']['signature']=="2")?"yes":"no",
       'signature' => $form_state['values']['signature'],
        //'is_pending' => ($form_state['values']['signature']=="yes")?$form_state['values']['signature']:"no",
        //'signature' => ($form_state['values']['signature']=="1")?$form_state['values']['signature']:"0",
       )
     )->execute();

/* Updating Capacity signature status from "2" to "0" */
     $updateCapacityId= $_REQUEST['capacity_id'];
     db_update('capacity_details')->fields(array('signature' => "0"))->condition('capacity_id', $updateCapacityId)->execute();
         if(isset($form_state['values']['signature']) && $form_state['values']['signature']=="2"){
              drupal_set_message('A copy has been saved to pending. You may now edit this document and save it.');
         }
     $form_state['redirect'] = 'capacity/'.$capacityId.'/edit';
   }else{

          if(isset($_REQUEST['capacity_id']) && $_REQUEST['capacity_id']!='')
            {
               $capacityId= $_REQUEST['capacity_id'];
              db_update('capacity_details')
              ->fields(array(
          	 'contributing_factor_models' => serialize($conArrModels),
                'intervention_models' => serialize($invArrModels),
                'Record' => $form_state['values']['Record'],
                'Record_meeting' => $form_state['values']['Record_meeting'],
                'Record_tranning' => $form_state['values']['Record_tranning'],
                'personConductingContent' => $person_conductin_data,
                'contactContent'=>$contact_list_data,
                'startdatetime' => $form_state['values']['startdatetime'],
                'enddatetime' => $form_state['values']['enddatetime'],
                'Length_of_services' => $form_state['values']['Length_of_services'],
                'location' => $form_state['values']['location'],
                'country' => $form_state['values']['Country'],
                'address_1' => $form_state['values']['address_1'],
                'address_2' => $form_state['values']['address_2'],
                'city' => $form_state['values']['city'],
                'states' => $form_state['values']['states'],
                'zip_code' => $form_state['values']['zip_code'],
                'number_adult_served' => $form_state['values']['number_adult_served'],
                'number_youth_served' => $form_state['values']['number_youth_served'],
                'number_business_attending' => $form_state['values']['number_business_attending'],
                'description_of_purpose' => $form_state['values']['description_of_purpose'],
                'description_of_outcome' => $form_state['values']['description_of_outcome'],
                'Members_Invloved' => $members_invloved_data,
                'Donation_select' => $Donation_select_data,
                'Monetary_Value' => $Monetary_Value_data,
                'Comment' => $Comment_data,
                'user_id'=>$user->uid,
                'Attachments_fid' => (isset($file_upload_ids) && count($file_upload_ids)>"0")?serialize($file_upload_ids):"",
                'Attachments_notes' => $form_state['values']['Attachments_notes'],
                'is_pending' => ($form_state['values']['signature']=="0" || $form_state['values']['signature']=="2")?"yes":"no",
                'signature' => $form_state['values']['signature'],
                 //'is_pending' => ($form_state['values']['signature']=="yes")?$form_state['values']['signature']:"no",
                 //'signature' => ($form_state['values']['signature']=="1")?$form_state['values']['signature']:"0",
                )
              )
              ->condition('capacity_id', $capacityId)
              ->execute();

              $form_state['redirect'] = 'capacity/'.$capacityId.'/view';
            }

    }

  $cap_info_check_id = db_query('SELECT MAX(capacity_info_id) FROM {capacity_details_info}')->fetchField();//echo $cap_info_check_id;die;

 $cap_info_check = db_query('SELECT updated_uid FROM {capacity_details_info} WHERE capacity_id = :capacity_id AND capacity_info_id = :capacity_info_id', array(':capacity_id' => $capacityId,':capacity_info_id' => $cap_info_check_id))->fetchField();

 $updatedUserId=$form_state['values']['updated_user_id']; //echo $cap_info_check."==".$updatedUserId;die;

 if($cap_info_check!='' && $cap_info_check==$updatedUserId){
    $capacity_update_info_id=db_update('capacity_details_info')
     ->fields(array(
          'capacity_id' => $capacityId,
          'updated_uid' => $form_state['values']['updated_user_id'],
          'updated_at' => $form_state['values']['updated_time'],
       )
     )
     ->condition('capacity_info_id', $cap_info_check_id)
     ->execute();
}else{
 $capacity_update_info_id = db_insert('capacity_details_info')->fields(array(
    'capacity_id' => $capacityId,
    'updated_uid' => $form_state['values']['updated_user_id'],
    'updated_at' => $form_state['values']['updated_time'],
   )
 )
 ->execute();
 }

  //
  // else
  // {
  // drupal_set_message('No data');
  // }
}


function capacity_item_form_submit($form, &$form_state)
{

  global $user;
//echo "<pre>";print_r($_REQUEST);die;

if(isset($form_state['values']['Record_meeting']) && $form_state['values']['Record_meeting']!=''){
    $eventTitle=$form_state['values']['Record_meeting'];
}else{
    $eventTitle=$form_state['values']['Record_tranning'];
}
$eventStartDate=$form_state['values']['startdatetime'];
$eventEndDate=$form_state['values']['enddatetime'];
$event_status=(isset($form_state['values']['signature']) && $form_state['values']['signature'] == "yes") ? "Pending" : "Completed";
/* Calendar Event Creation */
$event_node_id=create_data_event_node($eventTitle, $user->uid,$createdDate,$changedDate,$event_type="Capacity", $status="1",$eventStartDate,$eventEndDate,$event_status);

	 $query = db_select('planning_details','a');
      $query->fields('a', array('planning_id','title'));
      $query->orderBy('a.title','ASC');
      $planning_lists = $query->execute()->fetchAll();//echo "<pre>";print_r($_REQUEST);die;
	  				  $lmCount=0;
		  foreach($planning_lists as $plankey=>$planVal){
				$plan_id=$planVal->planning_id;
				$planning_data_lists = db_query("SELECT * FROM {planning_details} WHERE planning_id = ".$plan_id)->fetchAll();
			$chkSerialize = @unserialize($planning_data_lists[0]->contributing_factor);
			if ($chkSerialize !== false) {
				$contributingFactor=unserialize($planning_data_lists[0]->contributing_factor);
                $interventionsCheckedItems=unserialize($planning_data_lists[0]->interventions);
				$logicModelCount=count($contributingFactor['contributingCollection']);
				 for($i=0;$i<$logicModelCount;$i++){
					 if(isset($_REQUEST['contributing_factor'.$plankey.'_'.$i])){
						$cfLogicModels['contributing_factor'.$plankey.'_'.$i]=$_REQUEST['contributing_factor'.$plankey.'_'.$i];
				     }
					 for($inv=0;$inv<count($_REQUEST['interventions'.$plankey.'_'.$i]);$inv++){
						 if(isset($_REQUEST['interventions'.$plankey.'_'.$i])){
							$inLogicModels['interventions'.$plankey.'_'.$i]=$_REQUEST['interventions'.$plankey.'_'.$i];
					    }
				     }
				 }

			}else{
				   if(isset($_REQUEST['contributing_factor'.$plankey.'_'.$lmCount])){
				     $cfLogicModels['contributing_factor'.$plankey.'_'.$lmCount]=$_REQUEST['contributing_factor'.$plankey.'_'.$lmCount];
				   }
					 for($inv=0;$inv<count($_REQUEST['interventions'.$plankey.'_'.$lmCount]);$inv++){
						 if(isset($_REQUEST['interventions'.$plankey.'_'.$lmCount])){
							$inLogicModels['interventions'.$plankey.'_'.$lmCount]=$_REQUEST['interventions'.$plankey.'_'.$lmCount];
					     }
				     }
				$lmCount++;
			}

		  }//echo "<pre>";print_r($inLogicModels);die;
		  $conArrModels['contributing_factor']=$cfLogicModels;
		  $invArrModels['interventions']=$inLogicModels;


$person_conducting="";
if(count($_REQUEST['person_conducting'])>0){
for($i=0;$i<count($_REQUEST['person_conducting']);$i++){
 $person_conducting['person_conducting'][$i]=$_REQUEST['person_conducting'][$i];
}
}
$person_conductin_data=serialize($person_conducting);

$contact_list="";
if(count($_REQUEST['contact_person_conducting'])>0){
for($i=0;$i<count($_REQUEST['contact_person_conducting']);$i++){
 $contact_list['contact_list'][$i]=$_REQUEST['contact_person_conducting'][$i];
}
}
$contact_list_data=serialize($contact_list);





  /*$values = $form_state['values'];
  if ($file = $values['Attachments']) {
  unset($values['Attachments_upload']);
  $filename = file_unmanaged_copy($file->url);
  $values['Attachments'] = $filename;
 }
  variable_set('Attachments', $values['Attachments']);
   $item = $form['#item'];*/

  if(isset($_REQUEST['Attachments_fid']['files']) && count($_REQUEST['Attachments_fid']['files'])>0){
	  $ui=0;
	  foreach($_REQUEST['Attachments_fid']['files'] as $uploadId=>$uploadVal ){
			$file_upload_ids['upload_id'][$ui]=$uploadId;
			$ui++;
	  }
  }


$Members_Invloved="";
if(count($_REQUEST['Members_Invloved'])>0){
for($i=0;$i<count($_REQUEST['Members_Invloved']);$i++){
 $Members_Invloved['Members_Invloved'][$i]=$_REQUEST['Members_Invloved'][$i];
}
}
$members_invloved_data=serialize($Members_Invloved);

$counts = $_REQUEST['hidden_field'];


$Donation_select=$Monetary_Value=$Comment=array();
if(count($_REQUEST['Donation_select'])>0){
$i = 0;
foreach ($_REQUEST['Donation_select'] as $keyz => $valuez) {
    $Donation_select['Donation_select'][$i]=$valuez;
    $Monetary_Value['Monetary_Value'][$i]=$_REQUEST['Monetary_Value'][$keyz];
    $Comment['Comment'][$i]=$_REQUEST['Comment'][$keyz];
    $i++;
  }
}
$Donation_select_data=serialize($Donation_select);
$Monetary_Value_data=serialize($Monetary_Value);
$Comment_data=serialize($Comment);

    $capacity_id = db_insert('capacity_details')

    ->fields(array(
	  'contributing_factor_models' => serialize($conArrModels),
      'intervention_models' => serialize($invArrModels),
      'Record' => $form_state['values']['Record'],
      'Record_meeting' => $form_state['values']['Record_meeting'],
      'Record_tranning' => $form_state['values']['Record_tranning'],
      'personConductingContent' => $person_conductin_data,
      'contactContent'=>$contact_list_data,
      'startdatetime' => $form_state['values']['startdatetime'],
      'enddatetime' => $form_state['values']['enddatetime'],
      'Length_of_services' => $form_state['values']['Length_of_services'],
      'location' => $form_state['values']['location'],
      'country' => $form_state['values']['Country'],
      'address_1' => $form_state['values']['address_1'],
      'address_2' => $form_state['values']['address_2'],
      'city' => $form_state['values']['city'],
      'states' => $form_state['values']['states'],
      'zip_code' => $form_state['values']['zip_code'],
      'number_adult_served' => $form_state['values']['number_adult_served'],
      'number_youth_served' => $form_state['values']['number_youth_served'],
      'number_business_attending' => $form_state['values']['number_business_attending'],
      'description_of_purpose' => $form_state['values']['description_of_purpose'],
      'description_of_outcome' => $form_state['values']['description_of_outcome'],
      'Members_Invloved' => $members_invloved_data,
       'Donation_select' => $Donation_select_data,
      'Monetary_Value' => $Monetary_Value_data,
      'Comment' => $Comment_data,
      'user_id' => $user->uid,
      'event_node_id' => $event_node_id,
      'Attachments_fid' => (isset($file_upload_ids) && count($file_upload_ids)>"0")?serialize($file_upload_ids):"",
      'Attachments_notes' => $form_state['values']['Attachments_notes'],
       'is_pending' => ($form_state['values']['signature']=="0" || $form_state['values']['signature']=="2")?"yes":"no",
       'signature' => $form_state['values']['signature'],
      )
    )
    ->execute();


    //$capacity_id = Database::getConnection()->lastInsertId('capacity_id');

    $capacity_info_id = db_insert('capacity_details_info')->fields(array(
       'created_uid' => $form_state['values']['user_id'],
       'capacity_id' => $capacity_id,
       'created_at' => $form_state['values']['created_time'],
      )
    )
    ->execute();



foreach ($person_conducting['person_conducting'] as $key => &$val) {
   db_insert('person_conducting')->fields(array(
            'personConductingContent_id' =>$val,
            'capacity_id' => $capacity_id,
          ))->execute();
}



foreach ($Members_Invloved['Members_Invloved'] as $key => &$mval) {
   db_insert('Members_Involved_capacity')->fields(array(
            'Members_Invloved_id' =>$mval,
            'capacity_id' => $capacity_id,
          ))->execute();
}

    // $conArrModels['contributing_factor']=$cfLogicModels;
    //   $invArrModels['interventions']=$inLogicModels;
//echo "<pre>";print_r($cfLogicModels);die();

$lmCount1=0;
foreach($planning_lists as $plankey=>$planVal){
  $plan_id=$planVal->planning_id;
  $planning_data_lists = db_query("SELECT * FROM {planning_details} WHERE planning_id = ".$plan_id)->fetchAll();
  $chkSerialize = @unserialize($planning_data_lists[0]->contributing_factor);
  if ($chkSerialize !== false) {
          $contributingFactor=unserialize($planning_data_lists[0]->contributing_factor);
          $interventionsCheckedItems=unserialize($planning_data_lists[0]->interventions);
          $logicModelCount=count($contributingFactor['contributingCollection']);
   for($i=0;$i<$logicModelCount;$i++){
     if(isset($_REQUEST['contributing_factor'.$plankey.'_'.$i])){
      //$cfLogicModels['contributing_factor'.$plankey.'_'.$i]=$_REQUEST['contributing_factor'.$plankey.'_'.$i];
      db_insert('capacity_contributing_factor')->fields(array(
        'contributing_factor_id' => $_REQUEST['contributing_factor'.$plankey.'_'.$i],
        'capacity_id' => $capacity_id,
      ))->execute();
       }

       //echo "<pre>";print_r($_REQUEST);die();
     for($inv=0;$inv<count($_REQUEST['interventions'.$plankey.'_'.$i]);$inv++){
       if(isset($_REQUEST['interventions'.$plankey.'_'.$i])){
        //$inLogicModels['interventions'.$plankey.'_'.$i]=$_REQUEST['interventions'.$plankey.'_'.$i];
        db_insert('capacity_interventions')->fields(array(
          'interventions_id' => $_REQUEST['interventions'.$plankey.'_'.$i][$inv],
          'capacity_id' => $capacity_id,
          'contributing_factor_id' => $_REQUEST['contributing_factor'.$plankey.'_'.$i],
        ))->execute();
        }
       }
   }

 }else{
     // if(isset($_REQUEST['contributing_factor'.$plankey.'_'.$lmCount])){
     //   $cfLogicModels['contributing_factor'.$plankey.'_'.$lmCount]=$_REQUEST['contributing_factor'.$plankey.'_'.$lmCount];
     // }
       for($inv=0;$inv<count($_REQUEST['interventions'.$plankey.'_'.$lmCount1]);$inv++){
         if(isset($_REQUEST['interventions'.$plankey.'_'.$lmCount1])){
          //$inLogicModels['interventions'.$plankey.'_'.$lmCount]=$_REQUEST['interventions'.$plankey.'_'.$lmCount];
          db_insert('capacity_interventions')->fields(array(
            'interventions_id' => $_REQUEST['interventions'.$plankey.'_'.$lmCount1][$inv],
            'capacity_id' => $capacity_id,
            'contributing_factor_id' => $_REQUEST['contributing_factor'.$plankey.'_'.$lmCount1],
          ))->execute();
           }
         }
       $lmCount1++;
  }

}



for($i=0;$i<$logicModelCount;$i++){
  if(isset($_REQUEST['contributing_factor'.$plankey.'_'.$i])){
   //$cfLogicModels['contributing_factor'.$plankey.'_'.$i]=$_REQUEST['contributing_factor'.$plankey.'_'.$i];

   db_insert('capacity_contributing_factor')->fields(array(
     'contributing_factor_id' => $_REQUEST['contributing_factor'.$plankey.'_'.$i],
     'capacity_id' => $capacity_id,
   ))->execute();

    }
  for($inv=0;$inv<count($_REQUEST['interventions'.$plankey.'_'.$i]);$inv++){
    if(isset($_REQUEST['interventions'.$plankey.'_'.$i])){
     $inLogicModels['interventions'.$plankey.'_'.$i]=$_REQUEST['interventions'.$plankey.'_'.$i];

     db_insert('capacity_interventions')->fields(array(
       'contributing_factor_id' => $_REQUEST['contributing_factor'.$plankey.'_'.$i],
       'capacity_id' => $capacity_id,
       'interventions_id' => $capacity_id,
     ))->execute();

     }
    }
}
    if(isset($capacity_id) && $capacity_id!='' && $form_state['values']['signature']=="2"){

        drupal_set_message('A copy has been saved to pending. You may now edit this document and save it.');
        $form_state['redirect'] = 'capacity/'.$capacity_id.'/edit';
    }else{
        $form_state['redirect'] = 'capacity/list';
    }
}


function capacity_view_list_item_page($item)
{



  global $user;
  $base_url=$GLOBALS['base_url'];
  $query = db_select('capacity_details','a');
  $query->fields('a', array('capacity_id','Record_meeting','is_pending'));
  $query->groupBy('a.Record_meeting');
  $query->orderBy('a.Record_meeting','ASC');
  $capacity_data_lists = $query->execute()->fetchAll();

  $capacityListItems="<div id='capacityDataLists' class='model_list_Section' ><h3>Record Meeting and Training / Technical Assistance Reports</h3><ul>";
  $capacityPendingListItems="<div id='capacityDataLists' class='model_list_Section' ><h3>Pending Record Meeting and Training / Technical Assistance Reports</h3><ul>";
		  $record_meeting_img = file_create_url(path_to_theme().'/images/doctor.png');
  if(isset($capacity_data_lists) && count($capacity_data_lists)>0){
      foreach($capacity_data_lists as $dataKey=>$dataItem){
     if($dataItem->Record_meeting!=''){
      if($dataItem->is_pending=='yes'){
			$capacityPendingListItems .='<li><div class="planning_list">
				<div class="left_Section">
					<img src='.$record_meeting_img.' class="white_img">
					<p><span>'.$dataItem->Record_meeting.'</span></p>
				</div>
				<div class="right_section">
					<a href="'.$base_url.'/capacity/'.$dataItem->capacity_id.'/view"><i class="fa fa-eye fa-lg" aria-hidden="true"></i></a>
					<a href="'.$base_url.'/capacity/'.$dataItem->capacity_id.'/edit"><i class="fa fa-pencil-square fa-lg" aria-hidden="true"></i></a>
				</div>
			</div></li>';
			}else{
			$capacityListItems .='<li><div class="planning_list">
				<div class="left_Section">
					<img src='.$record_meeting_img.' class="white_img">
					<p><span>'.$dataItem->Record_meeting.'</span></p>
				</div>
				<div class="right_section">
					<a href="'.$base_url.'/capacity/'.$dataItem->capacity_id.'/view"><i class="fa fa-eye fa-lg" aria-hidden="true"></i></a>
					<a href="'.$base_url.'/capacity/'.$dataItem->capacity_id.'/edit"><i class="fa fa-pencil-square fa-lg" aria-hidden="true"></i></a>
				</div>
			</div></li>';
		}
	   }
      }
  }else{
    $capacityListItems.='<p>No Capacity list found.</p>';
  }
  $capacityListItems.="</ul></div>";
  $capacityPendingListItems.="</ul></div>";

  if(isset($_GET['responce-msg']) && $_GET['responce-msg']!=''){
      $form['response-msg-status']=array(
        '#markup'=>'<div class="messages status">
    <h2 class="element-invisible">Status message</h2>
    <strong>'.$_GET['responce-msg'].'</strong> Assessment details successfully saved.</div>'
       );
    } else if(isset($_GET['update-msg']) && $_GET['update-msg']!=''){
      $form['response-msg-status']=array(
        '#markup'=>'<div class="messages status">
    <h2 class="element-invisible">Status message</h2>
    <strong>'.$_GET['update-msg'].'</strong> Assessment details updated successfully.</div>'
       );
    }
   $form['capacity_details_meeting']=array(
    '#markup'=>'<div class="field-items"><div class="field-item even" id="first"><p>The Capacity module is where you will enter meetings with resources, training and education activities for the Agency and new External users who gave Agreed to assist the Agency.<br>
<strong>How to</strong><br>
 <p>Meeting - Click the meeting link and put in all the relevant information regarding the meeting you had.<br>
 Training - Click the training link and put in all the relevant information regarding the training activity you had.<br>
 External User - Click the link and put in the contact information for the new Users.<br>
</div></div>'

   );

  $query = db_select('capacity_details','b');
  $query->fields('b', array('capacity_id','Record_tranning','is_pending'));
  $query->groupBy('b.Record_tranning');
  $query->orderBy('b.Record_tranning','ASC');
  $capacity_data_lists_Record_tranning = $query->execute()->fetchAll();

  $capacityListItems_Record_tranning="<div id='capacityDataLists'  class='model_list_Section' ><ul>";
  $capacityListItems_Record_tranning_pending="<div id='capacityDataLists'  class='model_list_Section' ><ul>";
	   $record_training_img = file_create_url(path_to_theme().'/images/doctor.png');
  if(isset($capacity_data_lists_Record_tranning) && count($capacity_data_lists_Record_tranning)>0){
      foreach($capacity_data_lists_Record_tranning as $dataKey=>$dataItem){
        //$capacityListItems_Record_tranning .='<tbody><tr><td><a href="'.$base_url.'/capacitycontent/'.$dataItem->capacity_id.'">'.$dataItem->Record_tranning.'</a> - <a href="'.$base_url.'/capacitycontent/'.$dataItem->capacity_id.'/edit"><b>Edit</b></a></td>';
        if($dataItem->Record_tranning!=''){
		  if($dataItem->is_pending=='yes'){
			  $capacityListItems_Record_tranning_pending .='<li><div class="planning_list">
			  <div class="left_Section">
				  <img src='.$record_training_img.' class="white_img">
				  <p><span>'.$dataItem->Record_tranning.'</span></p>
			  </div>
			  <div class="right_section">
				  <a href="'.$base_url.'/capacity/'.$dataItem->capacity_id.'/view"><i class="fa fa-eye fa-lg" aria-hidden="true"></i></a>
				  <a href="'.$base_url.'/capacity/'.$dataItem->capacity_id.'/edit"><i class="fa fa-pencil-square fa-lg" aria-hidden="true"></i></a>
			  </div>
			  </div></li>';
		  }else{
			  $capacityListItems_Record_tranning .='<li><div class="planning_list">
			  <div class="left_Section">
				  <img src='.$record_training_img.' class="white_img">
				  <p><span>'.$dataItem->Record_tranning.'</span></p>
			  </div>
			  <div class="right_section">
				  <a href="'.$base_url.'/capacity/'.$dataItem->capacity_id.'/view"><i class="fa fa-eye fa-lg" aria-hidden="true"></i></a>
				  <a href="'.$base_url.'/capacity/'.$dataItem->capacity_id.'/edit"><i class="fa fa-pencil-square fa-lg" aria-hidden="true"></i></a>
			  </div>
			</div></li>';

		  }
      }
      }
  }else{
    //$capacityListItems_Record_tranning.='<tr><td colspan="3">No Capacity list found.</td></tr>';
    $capacityListItems_Record_tranning_pending.='<tr><td colspan="3">No Pending Capacity list found.</td></tr>';
  }
  $capacityListItems_Record_tranning.="</ul></div>";
  $capacityListItems_Record_tranning_pending.="</ul></div>";

  if(isset($_GET['responce-msg']) && $_GET['responce-msg']!=''){
      $form['response-msg-status']=array(
        '#markup'=>'<div class="messages status">
    <h2 class="element-invisible">Status message</h2>
    <strong>'.$_GET['responce-msg'].'</strong> Capacity details successfully saved.</div>'
       );
    } else if(isset($_GET['update-msg']) && $_GET['update-msg']!=''){
      $form['response-msg-status']=array(
        '#markup'=>'<div class="messages status">
    <h2 class="element-invisible">Status message</h2>
    <strong>'.$_GET['update-msg'].'</strong> capacity details updated successfully.</div>'
       );
    }

	$record_meeting_icon1 = file_create_url(path_to_theme().'/images/new_icon.png');
     $form['capacity_details_block_start1']=array(
    '#markup'=>'
	<div class="capacityDataLists_new model_list_Section">
		<ul>
			<li><div class="planning_list">
					<div class="left_Section">
						<a href="add_resource"><img src='.$record_meeting_icon1.' class="white_img">
						<p><span>Manage Resources / Add a Resources</span></p></a>
					</div>
				</div>
			</li>
			<li>
				<div class="planning_list">
					<div class="left_Section">
						<a href="schedule_meeting">
							<img src='.$record_meeting_icon1.' class="white_img">
							<p><span>Schedule a Meeting / Planning / Calendar</span></p>
						</a>
					</div>
				</div>
			</li>
		</ul>
	</div>
	<div class="capacity_btn_section">
	<div class="capacity-nxt-btn submit_button"><a href="add?type=meeting"><img src='.$record_meeting_icon1.' class="white_img"><span>Create Record a Meeting</span></a></div>
	<div class="capacity-nxt-btn submit_button"><a href="add?type=training"><img src='.$record_meeting_icon1.' class="white_img"><span>Create Record Training / Technical Assistance</span></a></div>
  <div class="capacity-nxt-btn submit_button"><a href="add?type=reminder"><img src='.$record_meeting_icon1.' class="white_img"><span>Create Reminder</span></a></div>
	</div><br><br><hr>');

		$form['capacity_details_meeting_pending']=array(
				'#markup'=>'<p style="margin-left:20px;">
					'.$capacityPendingListItems.'
					'.$capacityListItems_Record_tranning_pending.'
					</p><hr>');


		$form['capacity_details_meeting1']=array(
				'#markup'=>'<p style="margin-left:20px;">
					'.$capacityListItems.'
					'.$capacityListItems_Record_tranning.'
					</p>');

   return $form;
}

function capacity_view_add_resource_page(){
  global $base_url;
	$record_meeting_icon1 = file_create_url(path_to_theme().'/images/new_icon.png');
		$resourcesLinks='<div class="capacityDataLists_new model_list_Section"><ul style="list-style-type: none;">
<li><div class="planning_list"><p><img src='.$record_meeting_icon1.' class="white_img"><span><a href="'.$base_url.'/e-star-admin/register">Add an Admininstrator</span></a></p></div></li>
<li><div class="planning_list"><p> <img src='.$record_meeting_icon1.' class="white_img"><span><a href="'.$base_url.'/e-star-manager/register">Add a Manager</span></a></p></div></li>
<li><div class="planning_list"><p><img src='.$record_meeting_icon1.' class="white_img"><span><a href="'.$base_url.'/e-star-staff/register">Add a Staff</span></a></p></div></li>
<li><div class="planning_list"><p><img src='.$record_meeting_icon1.' class="white_img"><span><a href="'.$base_url.'/e-star-volunteers/register">Add a Volunteer </span></a></p></div></li>
<li><div class="planning_list"><p><img src='.$record_meeting_icon1.' class="white_img"><span><a href="'.$base_url.'/contact/add">Add a Contact (External User) </span></a></p></div></li>
<li><div class="planning_list"><p><img src='.$record_meeting_icon1.' class="white_img"><span><a href="'.$base_url.'/team_manager">Add a Team </span></a></p></div></li>
<li><div class="planning_list"><p><img src='.$record_meeting_icon1.' class="white_img"><span><a href="'.$base_url.'/hr-overview">View HR Overview </span></a></p></div></li>
<li><div class="planning_list"><p><img src='.$record_meeting_icon1.' class="white_img"><span><a href="'.$base_url.'/contact/list">View Contacts </span></a></p></div></li>
<li><div class="planning_list"><p><img src='.$record_meeting_icon1.' class="white_img"><span><a href="'.$base_url.'/team_manager/list">View Teams </span></a></p></div></li>
</ul></div>';

return $resourcesLinks;

}

function capacity_view_schedule_meeting_page(){
  $base_url=$GLOBALS['base_url'];
	$record_meeting_icon1 = file_create_url(path_to_theme().'/images/new_icon.png');
		$meetingLinks='<div class="capacityDataLists_new model_list_Section"><ul style="list-style-type: none;">
<li><div class="planning_list"><p><img src='.$record_meeting_icon1.' class="white_img"><span><a href="'.$base_url.'/event-created/">Calendar</span></a></p></div></li>

<li><div class="planning_list"><p><img src='.$record_meeting_icon1.' class="white_img"><span><a href="'.$base_url.'/communication_tool/add">Communications Tools</span></a></p></div></li>

<li><div class="planning_list"><p><img src='.$record_meeting_icon1.' class="white_img"><span><a href="#">Create an implementation Report Event</span></a></p></div></li>

<li><div class="planning_list"><p><img src='.$record_meeting_icon1.' class="white_img"><span><a href="#">Create an capacity Report Event</span></a></p></div></li>

<li><div class="planning_list"><p><img src='.$record_meeting_icon1.' class="white_img"><span><a href="'.$base_url.'/file_system_library">Files</span></a></p></div></li>

</ul></div>';

return $meetingLinks;

}

/* For Event Calandar creation */
function create_data_event_node($title, $uid, $createdDate,$changedDate,$event_type, $status,$eventStartDate,$eventEndDate,$event_status) {
    $node = new stdClass();
    $node->type = "event_calendar";
    $node->title = $title;
    $node->language = LANGUAGE_NONE;
    $node->uid = $uid;
    $node->created = $createdDate;
    $node->changed = $changedDate;
    node_object_prepare($node);


    //$user=user_load($uid);
    //$username=$user->name;

    $node->field_user_id[und][0]['value']=$uid;
    $node->field_event_status[und][0]['value']=$event_status;
    $node->field_event_type[und][0]['value']=$event_type;

    $node = node_submit($node);
    node_save($node);
    $startDate= $eventStartDate;
    $endDate= $eventEndDate;
    if(isset($node->nid) && $node->nid!=''){
      $nodeId=$node->nid;
          $nid = db_insert('field_data_event_calendar_date')
          ->fields(array(
            'entity_type' => 'node',
            'bundle' => 'event_calendar',
            'deleted' => 0,
            'entity_id' => $nodeId,
            'revision_id' => $nodeId,
            'language' => 'und',
            'delta' => 0,
            'event_calendar_date_value' => $startDate,
            'event_calendar_date_value2' => $endDate,
          ))
          ->execute();
          return $nodeId;
  }

}

/* To COnvert users fields from text to dropdown with form_alter hook */
function capacity_form_alter(&$form, $form_state, $form_id) { //echo $form['#id'].'<>>'.$form_id;die;
switch($form_id) {
  case 'views_exposed_form':
      // Over-ride Views exposed filter for Captain so it replaces the text field with a select list populated by captains marked as paid in a Webform table
      if ($form['#id'] == 'views-exposed-form-calendar-page-1' || $form['#id']=='views-exposed-form-calendar-page-2' || $form['#id']=='views-exposed-form-calendar-page-3' || $form['#id']=='views-exposed-form-calendar-page') {
            // Using dpm with Devel installed to give me array data on the Views form
            //dpm($form);
            $form['field_user_id_value']['#type'] = "select";
            $form['field_user_id_value']['#size'] = null;
            $users[''] = t('-- All Users --');
            $query = db_query("
              SELECT uid,name
              FROM {users}
              WHERE uid!='0'")->fetchAll();//echo "<pre>";print_r($query);die();

             // Run through the results
             foreach($query as $result) { //echo "<pre>";print_r($result);die();

                 $construct = $result->name;
                 $users[$result->uid] = t($construct);

             }
             $form['field_user_id_value']['#options'] = $users;
             //$form['submit']['#value'] = t('Search');
         }
    break;
  }
}

?>
