<?php

/**
 * Implementation of hook_menu
 */
function e_star_contacts_menu() {
    $menu = array();
    $menu['contact_list'] = array
  (
    'title' => 'User Register',
    'page callback' => 'get_estar_contact_lists',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );

    return $menu;
}
/**
 * [estar get all contacts list]
 * @param  [type] $node [description]s
 * @return [type]       [description]
 */
function get_estar_contact_lists($form,&$form_state){
	//drupal_set_title("");
	$all_user_lists = entity_load('user');

$all_user_details = json_decode(json_encode($all_user_lists), true);

   //echo "<pre>";print_r($personConduct_id_arr);die;
   
   
    $form['membersInvolvedStart']=array('#markup'=>'<div class="responsive_table"><table id="contactMembersInvolvedTab" class="sticky-enabled table-select-processed">
 <thead><tr><th>First Name</th><th>Last Name</th><th>Company organization</th> <th>Email</th><th>Cell phone</th><th>Sector</th><th width="500px">Tools</th></tr></thead>
<tbody>');
  $membersRow='';
  foreach($all_user_details as $membersList){ //echo "<pre>";print_r($all_user_details);die;
      if($membersList['uid']!="0"){
		  $uID=$membersList['uid'];
        $last_name_staff = db_query("SELECT field_last_name_value FROM field_data_field_last_name WHERE entity_id =".$membersList['uid'])->fetchField();//echo $last_name_staff."<pre>";print_r($usersList);die;
        $cell_phone = db_query("SELECT field_cell_phone_value FROM field_data_field_cell_phone WHERE entity_id =".$membersList['uid'])->fetchField();
        $org_name = db_query("SELECT field_company_organization_value FROM field_data_field_company_organization WHERE entity_id =".$membersList['uid'])->fetchField();
        
        $membersRow.='<tr class=""><td>'.$membersList['name'].'</td><td>'.(($last_name_staff!="")?$last_name_staff:"").'</td>
        <td>'.(($org_name!="")?$org_name:"").'</td><td>'.$membersList['mail'].'</td>
              <td>'.(($cell_phone!="")?$cell_phone:"").'</td><td></td><td class="user_action_section"><a class="user_class" href="user/'.$uID.'"><i class="fa fa-eye" aria-hidden="true"></i> <span>View</span></a> <a class="edit_class" href="user/'.$uID.'/edit?destination=admin/people">
 <i class="fa fa-pencil-square-o" aria-hidden="true"></i><span>Edit</span></a> <a class="inactive_class" href="user/'.$uID.'/cancel?destination=admin/people"> <i class="fa fa-times" aria-hidden="true"></i>
<span>Make Inactive</span></a></td></tr>';
      }
    
  }
  
   $form['Members_Invloved']=array('#markup'=>$membersRow);
     
   $form['membersInvolvedEnd']=array('#markup'=>'</tbody></table></div>');
   
   return $form;
	
}
?>
