<?php
//include_once('mailtest.php');
/**
 * MOU Manager of hook_menu
 */
function team_manager_menu() {
    $menu = array();
    $menu['team_manager'] = array
  (
    'title' => 'Create Team Manager',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('team_manager_form'),
    'access callback' => TRUE,
  );
  $menu['team_manager/view/%'] = array
(
  'title' => 'Team Manager View',
  'page callback' => 'drupal_get_form',
  'page arguments' => array('get_team_manager_details_view', 1),
  'access callback' => TRUE,
);
  $menu['team_manager/list'] = array
(
  'title' => 'Team Manager List',
  'page callback' => 'get_team_manager_details_list',
  'page arguments' => array(2),
  'access callback' => TRUE,
);


    return $menu;
}

/**
 * [estar get all contacts list]
 * @param  [type] $node [description]s
 * @return [type]       [description]
 */
function team_manager_form(){
	//drupal_set_title("");
  global $user;
  $form=array();
	$all_user_lists = entity_load('user');

$all_user_details = json_decode(json_encode($all_user_lists), true);

   //echo "<pre>";print_r($all_user_details);die;

   //echo "<pre>";print_r($personConduct_id_arr);die;

   $form['team_name'] = array(
       '#type' => 'textfield',
       '#title' => t('Team Name'),
       '#required'=>TRUE,
       '#attributes' => array('id'=>"team-id"),
   );

   $form['person_Conducting_starts'] = array(
       '#markup' => "<div id='person_Conducting_changehidden'>"
   );
   $form['personConducting'] = array(
       '#markup' => '<div class="responsive_table"><table id="personConductingTab" class="sticky-enabled table-select-processed">
 <thead><tr><th class="select-all"></th><th>First Name</th><th>Last Name</th><th>Email</th><th>Cell phone</th><th>Company Organization</th></tr></thead>
 <tbody>'
   );
   $usersRow = '';
   foreach ($all_user_details as $usersList)
   { //echo "<pre>";print_r($all_user_details);die;
       if ($usersList['uid'] != "0" && (isset($usersList['roles'][7]) && $usersList['roles'][7] == "Staff User") || (isset($usersList['roles'][5]) && $usersList['roles'][5] == "Admin") || (isset($usersList['roles'][6]) && $usersList['roles'][6] == "Manager"))
       {
          $pid=db_query("SELECT pid FROM profile WHERE uid =" . $usersList['uid'])->fetchField();
           $last_name_staff = db_query("SELECT field_last_name_value FROM field_data_field_last_name WHERE entity_id =" . $pid)->fetchField();
           $cell_phone = db_query("SELECT field_cell_phone_value FROM field_data_field_cell_phone WHERE entity_id =" . $pid)->fetchField();
           $org_name = db_query("SELECT field_company_organization_value FROM field_data_field_company_organization WHERE entity_id =" . $pid)->fetchField();

           $usersRow .= '<tr class="odd"><td><div class="form-item form-type-checkbox form-item-person-conducting-0">
               <label><input id="teamManagerId" name="team_members[]" value="' . $usersList['uid'] . '" class="form-checkbox required" type="checkbox" title="Team manager"></label>

             </td><td>' . (($usersList['name'] != "") ? $usersList['name'] : "") . '</td><td>' . (($last_name_staff != "") ? $last_name_staff : "") . '</td>
             <td>' . (($usersList['mail'] != "") ? $usersList['mail'] : "") . '</td>
             <td>' . (($cell_phone != "") ? $cell_phone : "") . '</td>
             <td>' . (($org_name != "") ? $org_name : "") . '</td>
             </tr>';
       }

   }

   $contact_lists =db_query("SELECT * from {estar_contacts_details}")->fetchAll();
   //$usersRow = '';
  if(isset($contact_lists) && count($contact_lists)>0){
   foreach ($contact_lists as $usersList)
   { //echo "<pre>";print_r($all_user_details);die;
       if (isset($usersList) && $usersList!="")
       {
           $usersRow .= '<tr class="odd"><td><div class="form-item form-type-checkbox form-item-person-conducting-0">
               <label><input id="mouManagerId" name="team_members[]" value="' . $usersList->contact_id. '" class="form-checkbox required" type="checkbox" title="contact"></label>

             </td><td>' . (($usersList->first_name != "") ? $usersList->first_name : "") . '</td>
             <td>' . (($usersList->last_name != "") ? $usersList->last_name : "") . '</td>
             <td>' . (($usersList->email != "") ? $usersList->email : "") . '</td>
             <td>' . (($usersList->phone != "") ? $usersList->phone : "") . '</td>
             <td>' . (($usersList->organization != "") ? $usersList->organization : "") . '</td>
             </tr>';
       }

   }
 }else{
   $usersRow='';
 }


   $form['personConductingContent'] = array(
       '#markup' => $usersRow,
   );

   $form['personConductingEnd'] = array(
       '#markup' => '</tbody></table></div>'
   );
   $form['person_Conducting_end'] = array(
       '#markup' => '</div>'
   );

   $form['next_btn_div_start2'] = array(
       '#markup' => "<div class='assessment-nxt-btn implement-btn '>"
   );
   $form['submit'] = array(
       '#type' => 'submit',
       '#value' => t('Create Team') ,
   );
   $form['next_btn_div_end2'] = array(
       '#markup' => "</div><br>"
   );

   return $form;

}

function get_team_manager_details_view(){
        $form=array();
        $all_user_lists = entity_load('user');

        $url = (isset($_SERVER['HTTPS']) ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
           $teamId= basename($url);
          if(isset($teamId) && $teamId!=""){
              $team_details = db_query("SELECT * FROM {team_manager_details} WHERE team_manager_id = " . $teamId."")->fetchAll();
          }

if(isset($team_details) && count($team_details)>0){

      $all_user_details = json_decode(json_encode($all_user_lists), true);
  $teamMembers = unserialize($team_details[0]->team_members_id);
      //echo "<pre>";print_r($teamMembers);die;
         $form['team_name'] = array(
             '#type' => 'textfield',
             '#title' => t('Team Name'),
             '#default_value'=>$team_details[0]->team_name,
             '#required'=>TRUE,
             '#attributes'=>array('readonly'=>"readonly"),
             '#attributes' => array('id'=>"team-id"),
         );

         $form['person_Conducting_starts'] = array(
             '#markup' => "<div id='person_Conducting_changehidden'>"
         );
         $form['personConducting'] = array(
             '#markup' => '<div class="responsive_table"><table id="personConductingTab" class="sticky-enabled table-select-processed">
       <thead><tr><th class="select-all"></th><th>First Name</th><th>Last Name</th><th>Email</th><th>Cell phone</th><th>Company Organization</th></tr></thead>
       <tbody>'
         );
         $usersRow = '';
         foreach ($all_user_details as $usersList)
         { //echo "<pre>";print_r($all_user_details);die;
             if ($usersList['uid'] != "0" && (isset($usersList['roles'][7]) && $usersList['roles'][7] == "Staff User") || (isset($usersList['roles'][5]) && $usersList['roles'][5] == "Admin") || (isset($usersList['roles'][6]) && $usersList['roles'][6] == "Manager"))
             {
                $pid=db_query("SELECT pid FROM profile WHERE uid =" . $usersList['uid'])->fetchField();
                 $last_name_staff = db_query("SELECT field_last_name_value FROM field_data_field_last_name WHERE entity_id =" . $pid)->fetchField();
                 $cell_phone = db_query("SELECT field_cell_phone_value FROM field_data_field_cell_phone WHERE entity_id =" . $pid)->fetchField();
                 $org_name = db_query("SELECT field_company_organization_value FROM field_data_field_company_organization WHERE entity_id =" . $pid)->fetchField();
             $teamCheck = (in_array($usersList['uid'],$teamMembers['team_members'])) ? "checked=checked" : '';
             if(isset($teamMembers['team_members']) && in_array($usersList['uid'],$teamMembers['team_members'])){
                 $usersRow .= '<tr class="odd"><td><div class="form-item form-type-checkbox form-item-person-conducting-0">
                     <label><input '.$teamCheck.' readonly="readonly" id="teamManagerId" name="team_members[]" value="' . $usersList['uid'] . '" class="form-checkbox required" type="checkbox" title="Team manager"></label>

                   </td><td>' . (($usersList['name'] != "") ? $usersList['name'] : "") . '</td><td>' . (($last_name_staff != "") ? $last_name_staff : "") . '</td>
                   <td>' . (($usersList['mail'] != "") ? $usersList['mail'] : "") . '</td>
                   <td>' . (($cell_phone != "") ? $cell_phone : "") . '</td>
                   <td>' . (($org_name != "") ? $org_name : "") . '</td>
                   </tr>';
                 }
             }

         }

         $contact_lists =db_query("SELECT * from {estar_contacts_details}")->fetchAll();
         //$usersRow = '';
        if(isset($contact_lists) && count($contact_lists)>0){
         foreach ($contact_lists as $usersList)
         { //echo "<pre>";print_r($all_user_details);die;
             if (isset($usersList) && $usersList!="")
             {
               if(isset($teamMembers['team_members']) && in_array($usersList->contact_id,$teamMembers['team_members'])){
               $teamCheck = (in_array($usersList->contact_id,$teamMembers['team_members'])) ? "checked=checked" : '';
                 $usersRow .= '<tr class="odd"><td><div class="form-item form-type-checkbox form-item-person-conducting-0">
                     <label><input '.$teamCheck.' readonly="readonly" id="mouManagerId" name="team_members[]" value="' . $usersList->contact_id. '" class="form-checkbox required" type="checkbox" title="contact"></label>

                   </td><td>' . (($usersList->first_name != "") ? $usersList->first_name : "") . '</td>
                   <td>' . (($usersList->last_name != "") ? $usersList->last_name : "") . '</td>
                   <td>' . (($usersList->email != "") ? $usersList->email : "") . '</td>
                   <td>' . (($usersList->phone != "") ? $usersList->phone : "") . '</td>
                   <td>' . (($usersList->organization != "") ? $usersList->organization : "") . '</td>
                   </tr>';
                 }
             }

         }
       }else{
         $usersRow='';
       }


         $form['personConductingContent'] = array(
             '#markup' => $usersRow,
         );

         $form['personConductingEnd'] = array(
             '#markup' => '</tbody></table></div>'
         );
         $form['person_Conducting_end'] = array(
             '#markup' => '</div>'
         );

}else{
        $form['invalid-team-list']=array('#markup'=>'<tr><td colspan="3">Team not found.</td></tr>');
}

         return $form;
}

function team_manager_form_submit($form, &$form_state){ //echo "<pre>";print_r($form_state);die;
global $user;

$Members_Invloved = "";
if (count($_REQUEST['team_members']) > 0)
{
    for ($i = 0;$i < count($_REQUEST['team_members']);$i++)
    {
        $Members_Invloved['team_members'][$i] = $_REQUEST['team_members'][$i];
    }
}
$members_invloved_data = serialize($Members_Invloved);

  $team_date_creation = date("F j, Y");
  $team_id = db_insert('team_manager_details')->fields(array(
    'team_name' => $form_state['input']['team_name'],
    'team_members_id' => $members_invloved_data,
    'creater_id' => $user->uid,
      'created_at' => $team_date_creation,
      'updated_at' => $team_date_creation,
  ))->execute();
  if($team_id!=''){
    $form_state['redirect'] = 'team_manager/list';
    drupal_set_message("Team created successfully");
  }
}

function get_team_manager_details_list(){

  $query = db_select('team_manager_details','a');
	$query->fields('a', array('team_manager_id','team_name'));
	$query->orderBy('a.team_name','ASC');
	$team_lists = $query->execute()->fetchAll();

  if(isset($team_lists) && count($team_lists)>0){

      foreach($team_lists as $dataKey=>$dataItem){
        $teamListItems .='<li><a href="view/'.$dataItem->team_manager_id.'"><span>'.$dataItem->team_name.'</span></a></li>';
      }
  }else{

		$teamListItems.='<tr><td colspan="3">No teams found.</td></tr>';

	}

    $form['team-manager-list']=array(
      '#markup'=>'<div class="planningDataList model_list_Section">
      <ul>
      '.$teamListItems.'
      </ul>
        </div>'
    );

    return $form;

}
?>
