<?php
//include_once('mailtest.php');
/**
 * MOU Manager of hook_menu
 */
function capacity_communication_tool_menu() {
    $menu = array();
    $menu['communication_tool/add'] = array
  (
    'title' => 'Communication Tool',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('communication_tool_add_form'),
    'access callback' => TRUE,
  );

$menu['communication_tool/add/list_members'] = array(
    'title' => 'Communication Tool List',
    'page callback' => 'communication_tool_list_form',
    'page arguments' => array(1) ,
    'access callback' => true,
);


    return $menu;
}


function capacity_communication_tool_init(){
  drupal_add_js(libraries_get_path('tinymce') . '/js/tinymce.min.js');
  drupal_add_js(drupal_get_path('module', 'mou_manager') .'/js/datatables.min.js', 'file');
  drupal_add_css(drupal_get_path('module', 'mou_manager') .'/css/datatables.min.css', 'file');
  global $all_user_lists,$all_user_details;
  	$all_user_lists = entity_load('user');
    $all_user_details = json_decode(json_encode($all_user_lists), true);
}

/**
 * [estar get all contacts list]
 * @param  [type] $node [description]s
 * @return [type]       [description]
 */
function communication_tool_add_form(){
	//drupal_set_title("");
  global $user,$all_user_lists,$all_user_details;
  $form=array();
	//$all_user_lists = entity_load('user');

   $form['sender_email'] = array(
       '#type' => 'textfield',
       '#title' => t('From what email address'),
       '#required'=>TRUE,
       '#default_value' => (isset($user->mail) && $user->mail!="")?$user->mail:"",
       '#attributes'=>array('readonly'=>"readonly")
   );
   $form['hid_username'] = array(
       '#type' => 'hidden',
       '#default_value' => (isset($user->name) && $user->name!="")?$user->name:"",
       '#attributes'=>array('id'=>"hidUserName")
   );
   $form['mail_subject'] = array(
       '#type' => 'textfield',
       '#required'=>TRUE,
       '#title' => t('Subject'),
   );
   $form['mail_body'] = array(
       '#type' => 'textarea',
       '#required'=>TRUE,
       '#title' => t('Body of Message'),
   );

  /* Display Team Lists */

  $form['team_list_starts'] = array(
      '#markup' => "<div id='person_Conducting_changehidden'>"
  );
  $form['team_list_contact'] = array(
      '#markup' => '<div id="teamMemberTabId" class="responsive_table"> <label style="color:green;">Team List <span class="form-required" title="This field is required.">*</span></label><table id="personConductingTab" class="sticky-enabled table-select-processed">
<thead><tr><th class="select-all"></th><th>Team Name</th></tr></thead>
<tbody>'
  );
  $team_lists =db_query("SELECT * from {team_manager_details}")->fetchAll();
  $teamUsersRow = '';
 if(isset($team_lists) && count($team_lists)>0){
  foreach ($team_lists as $teamList)
  { //echo "<pre>";print_r($team_lists);die;
      if (isset($teamList) && $teamList!="")
      {
          $teamUsersRow .= '<tr class="odd"><td><div class="form-item form-type-checkbox form-item-person-conducting-0">
              <label>
              <input id="teamManagerId" name="team_name[]" value="' . $teamList->team_manager_id. '" class="form-radio required teamManagerClass" type="radio" title="contact"></label>
              </td><td>' . (($teamList->team_name != "") ? $teamList->team_name : "") . '</td></tr>';
      }

  }
}else{
  $teamUsersRow='<tr><td colspan="6">Contacts list is empty.</td></tr>';
}

  $form['team_list_content'] = array(
      '#markup' => $teamUsersRow,
  );

  $form['team_list_contact_end'] = array(
      '#markup' => '</tbody></table></div>'
  );
  $form['team_list_contact_end1'] = array(
      '#markup' => '</div>'
  );
  $load_img = file_create_url(path_to_theme().'/images/Loading_icon.gif');
  $form['loading_icon']=array('#markup'=>"<div id='loadImgId' style='display:none;'><div class='loader_container'>
    <div class='loader_circle_outer animate'></div>
    <div class='loader_circle_inner'>
        <div class='loader2'></div>
    </div>
</div>
  </div>");

   //echo "<pre>";print_r($all_user_details);die;

   //echo "<pre>";print_r($personConduct_id_arr);die;
   $form['person_Conducting_starts'] = array(
       '#markup' => "<div id='person_Conducting_changehidden'>"
   );
   $form['personConducting'] = array(
       '#markup' => '<div id="teamTabId" class="responsive_table"> <table id="capUserListTab" class="sticky-enabled table-select-processed">
 <thead><tr><th class="select-all"><input id="capUserSelectAll" class="form-checkbox" title="Select all rows in this table" type="checkbox"></th><th>First Name</th><th>Last Name</th><th>Email</th><th>Cell phone</th><th>Company Organization</th></tr></thead>
 <tbody>'
   );
   $usersRow = '';
   foreach ($all_user_details as $usersList)
   { //echo "<pre>";print_r($all_user_details);die;
       if ($usersList['uid'] != "0" && (isset($usersList['roles'][7]) && $usersList['roles'][7] == "Staff User") || (isset($usersList['roles'][5]) && $usersList['roles'][5] == "Admin") || (isset($usersList['roles'][6]) && $usersList['roles'][6] == "Manager"))
       {
          $pid=db_query("SELECT pid FROM profile WHERE uid =" . $usersList['uid'])->fetchField();
           $last_name_staff = db_query("SELECT field_last_name_value FROM field_data_field_last_name WHERE entity_id =" . $pid)->fetchField();
           $cell_phone = db_query("SELECT field_cell_phone_value FROM field_data_field_cell_phone WHERE entity_id =" . $pid)->fetchField();
           $org_name = db_query("SELECT field_company_organization_value FROM field_data_field_company_organization WHERE entity_id =" . $pid)->fetchField();

           $usersRow .= '<tr class="odd"><td><div class="form-item form-type-checkbox form-item-person-conducting-0">
               <label><input id="teamManagerId" name="person_conducting[]" value="' . $usersList['uid'] . '" class="form-checkbox required " type="checkbox" title="manager"></label>

             </td><td>' . (($usersList['name'] != "") ? $usersList['name'] : "") . '</td><td>' . (($last_name_staff != "") ? $last_name_staff : "") . '</td>
             <td>' . (($usersList['mail'] != "") ? $usersList['mail'] : "") . '</td>
             <td>' . (($cell_phone != "") ? $cell_phone : "") . '</td>
             <td>' . (($org_name != "") ? $org_name : "") . '</td>
             </tr>';
       }

   }


   $form['personConductingContent'] = array(
       '#markup' => $usersRow,
   );

   $form['personConductingEnd'] = array(
       '#markup' => '</tbody></table></div>'
   );
   $form['person_Conducting_end'] = array(
       '#markup' => '</div>'
   );

   $form['contact_starts'] = array(
       '#markup' => "<div id='person_Conducting_changehidden'>"
   );
   $form['personContact'] = array(
       '#markup' => '<div class="responsive_table"> <label style="color:green;">Contact Lists <span class="form-required" title="This field is required.">*</span></label><table id="capContactListTab" class="sticky-enabled table-select-processed">
 <thead><tr><th class="select-all"><input id="capContactSelectAll" class="form-checkbox" title="Select all rows in this table" type="checkbox"></th><th>First Name</th><th>Last Name</th><th>Email</th><th>Phone</th><th>Company Organization</th><th>Primary Sector</th></tr></thead>
 <tbody>'
   );
   $contact_lists =db_query("SELECT * from {estar_contacts_details}")->fetchAll();
   $usersRow = '';
  if(isset($contact_lists) && count($contact_lists)>0){
   foreach ($contact_lists as $usersList)
   { //echo "<pre>";print_r($all_user_details);die;
       if (isset($usersList) && $usersList!="")
       {
         if(isset($usersList->primary_sector_select) && $usersList->primary_sector_select!=''){
              $primary_sector=get_taxonomy_term_name($usersList->primary_sector_select);
         }
           $usersRow .= '<tr class="odd"><td><div class="form-item form-type-checkbox form-item-person-conducting-0">
               <label><input id="teamManagerId" name="contact_person_conducting[]" value="' . $usersList->contact_id. '" class="form-checkbox required " type="checkbox" title="contact"></label>

             </td><td>' . (($usersList->first_name != "") ? $usersList->first_name : "") . '</td>
             <td>' . (($usersList->last_name != "") ? $usersList->last_name : "") . '</td>
             <td>' . (($usersList->email != "") ? $usersList->email : "") . '</td>
             <td>' . (($usersList->phone != "") ? $usersList->phone : "") . '</td>
             <td>' . (($usersList->organization != "") ? $usersList->organization : "") . '</td>
             <td>' . (($primary_sector != "") ? $primary_sector : "") . '</td></tr>';
       }

   }
 }else{
   $usersRow='<tr><td colspan="6">Contacts list is empty.</td></tr>';
 }


   $form['personContactContent'] = array(
       '#markup' => $usersRow,
   );

   $form['personContactEnd'] = array(
       '#markup' => '</tbody></table></div>'
   );
   $form['person_Contact_end'] = array(
       '#markup' => '</div>'
   );


   $form['next_btn_div_start2'] = array(
       '#markup' => "<div class='next_button'>"
   );
   $form['submit'] = array(
       '#type' => 'submit',
       '#value' => t('Send Mail') ,
   );
   $form['next_btn_div_end2'] = array(
       '#markup' => "</div>"
   );

   $form['submit-btn-separator'] = array(
       '#markup' => ''
   );

   return $form;

}


function communication_tool_list_form(){ //echo "<pre>";print_r($_REQUEST);die;
  global $all_user_lists,$all_user_details;
      if(isset($_REQUEST['team_id']) && $_REQUEST['team_id']!=""){
             $teamIds=explode("?",$_REQUEST['team_id']);
             $teamId=$teamIds[0];
            $team_members_list =db_query("SELECT team_members_id,team_name from {team_manager_details} WHERE team_manager_id=".$teamId)->fetchAll();
            if(isset($team_members_list[0]) && $team_members_list[0]->team_members_id!=''){
              $team_members=unserialize($team_members_list[0]->team_members_id);
            }//echo "<pre>";print_r($all_user_details);die;
            $team_name=$team_members_list[0]->team_name;
            $form['personConductingAlter'] = array(
                '#markup' => '<label style="color:green;">'.$team_name.'</label><table id="capTeamListTab" class="sticky-enabled table-select-processed">
          <thead><tr><th class="select-all"><input id="capTeamSelectAll" class="form-checkbox" title="Select all rows in this table" type="checkbox"></th><th>First Name</th><th>Last Name</th><th>Email</th><th>Cell phone</th><th>Company Organization</th></tr></thead>
          <tbody>'
            );
            $usersRow = '';
            foreach ($all_user_details as $usersList)
            {
                if ($usersList['uid'] != "0" && (isset($usersList['roles'][7]) && $usersList['roles'][7] == "Staff User") || (isset($usersList['roles'][5]) && $usersList['roles'][5] == "Admin") || (isset($usersList['roles'][6]) && $usersList['roles'][6] == "Manager"))
                {
                   $pid=db_query("SELECT pid FROM profile WHERE uid =" . $usersList['uid'])->fetchField();
                    $last_name_staff = db_query("SELECT field_last_name_value FROM field_data_field_last_name WHERE entity_id =" . $pid)->fetchField();
                    $cell_phone = db_query("SELECT field_cell_phone_value FROM field_data_field_cell_phone WHERE entity_id =" . $pid)->fetchField();
                    $org_name = db_query("SELECT field_company_organization_value FROM field_data_field_company_organization WHERE entity_id =" . $pid)->fetchField();
                //  $teamCheck = (in_array($usersList['uid'],$teamMembers['team_members'])) ? "checked=checked" : '';
               if(isset($team_members['team_members']) && count($team_members['team_members'])>0 && in_array($usersList['uid'],$team_members['team_members'])){
                 //$teamCheck = (in_array($usersList['uid'],$team_members['team_members'])) ? "checked=checked" : '';

                    $usersRow .= '<tr class="odd"><td><div class="form-item form-type-checkbox form-item-person-conducting-0">
                        <label><input id="teamManagerId" name="person_conducting[]" value="' . $usersList['uid'] . '" class="form-checkbox required " type="checkbox" title="manager" '.$teamCheck.'></label>

                      </td><td>' . (($usersList['name'] != "") ? $usersList['name'] : "") . '</td><td>' . (($last_name_staff != "") ? $last_name_staff : "") . '</td>
                      <td>' . (($usersList['mail'] != "") ? $usersList['mail'] : "") . '</td>
                      <td>' . (($cell_phone != "") ? $cell_phone : "") . '</td>
                      <td>' . (($org_name != "") ? $org_name : "") . '</td>
                      </tr>';
               }
            }

            }

            $contact_lists =db_query("SELECT * from {estar_contacts_details}")->fetchAll();
           if(isset($contact_lists) && count($contact_lists)>0){
            foreach ($contact_lists as $usersList)
            { //echo "<pre>";print_r($all_user_details);die;
                if (isset($usersList) && $usersList!="" && in_array($usersList->contact_id,$team_members['team_members']))
                {
                  if(isset($usersList->primary_sector_select) && $usersList->primary_sector_select!=''){
                       $primary_sector=get_taxonomy_term_name($usersList->primary_sector_select);
                  }
                    $usersRow .= '<tr class="odd"><td><div class="form-item form-type-checkbox form-item-person-conducting-0">
                        <label><input id="teamManagerId" name="contact_person_conducting[]" value="' . $usersList->contact_id. '" class="form-checkbox required " type="checkbox" title="contact"></label>

                      </td><td>' . (($usersList->first_name != "") ? $usersList->first_name : "") . '</td>
                      <td>' . (($usersList->last_name != "") ? $usersList->last_name : "") . '</td>
                      <td>' . (($usersList->email != "") ? $usersList->email : "") . '</td>
                      <td>' . (($usersList->phone != "") ? $usersList->phone : "") . '</td>
                      <td>' . (($usersList->organization != "") ? $usersList->organization : "") . '</td>
                      </tr>';
                }

            }
          }


            $form['personConductingContentAlter'] = array(
                '#markup' => $usersRow,
            );

            $form['personConductingEndAlter'] = array(
                '#markup' => '</tbody></table>'
            );
print drupal_render($form);
      }
}

function communication_tool_add_form_submit($form, &$form_state){
            global $user,$bcc_email_for_pstar;
//echo "<pre>";print_r($_REQUEST);die;

    if(isset($_REQUEST['person_conducting']) && count($_REQUEST['person_conducting'])>0){

          for($ci=0;$ci<count($_REQUEST['person_conducting']);$ci++){

            $personId=$_REQUEST['person_conducting'][$ci];
             $to=db_query("SELECT mail FROM users WHERE uid =" . $personId)->fetchField();

              $from = $form_state['input']['sender_email'];
              //$to      = $toMailId;
              $subject = $form_state['input']['mail_subject'];
              $message = $form_state['input']['mail_body'];
              $mail_res = sendInvitationMail($from, $to, $bcc_email_for_pstar, $subject, $message, $headers);

              if ($mail_res!="failed"){
                  drupal_set_message('An email has been sent to ' . $mail_res);
              }else{
                  drupal_set_message('Mail sending failed. Try after sometimes. ');
              }
          }
    }   if(isset($_REQUEST['contact_person_conducting']) && count($_REQUEST['contact_person_conducting'])>0){

            for($ci=0;$ci<count($_REQUEST['contact_person_conducting']);$ci++){

              $personId=$_REQUEST['contact_person_conducting'][$ci];
               $toMailId=db_query("SELECT email FROM estar_contacts_details WHERE contact_id =" . $personId)->fetchField();

                $from = $form_state['input']['sender_email'];
                //$to      = $toMailId;
                $subject = $form_state['input']['mail_subject'];
                $message = $form_state['input']['mail_body'];
                $mail_res = sendInvitationMail($from, $toMailId, $bcc_email_for_pstar, $subject, $message, $headers);

                if ($mail_res!="failed"){
                    drupal_set_message('An email has been sent to ' . $mail_res);
                }else{
                    drupal_set_message('Mail sending failed. Try after sometimes. ');
                }
            }
      }
}

function sendInvitationMail($from, $to, $bcc_email_for_pstar, $subject, $message, $headers){
  $headers = 'From: '.$from. "\r\n" .
      'Bcc: '.$bcc_email_for_pstar. "\r\n" .
      'X-Mailer: PHP/' . phpversion()."\r\n" .'MIME-Version: 1.0'."\r\n" .'Content-type: text/html; charset=iso-8859-1';

  if (mail($to, $subject, $message, $headers))
  {
      return $to;
  }
  else
  {
      return 'failed';
  }

}


?>
